### ISSUE TITLE
[Overlay ECMP]vnetRouteCheck' status failed with Overlay ecmp configurations

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#10604]
#### Description
When Overlay ECMP configs are added we see error logs with the below message.

Apr 18 16:28:03.894467 r-leopard-58 ERR monit[533]: 'vnetRouteCheck' status failed (1) -- Traceback (most recent call last):#012  File "/usr/local/bin/vnet_route_check.py", line 364, in <module>#012    sys.exit(main())#012  File "/usr/local/bin/vnet_route_check.py", line 335, in main#012    app_db_vnet_routes = get_vnet_routes_from_app_db()#012  File "/usr/local/bin/vnet_route_check.py", line 227, in get_vnet_routes_from_app_db#012    intf = vnet_intfs[vnet_name][0]#012KeyError: 'Vnet_v4_in_v6-0'

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202012_rc.7-43085dc50_Internal
Distribution: Debian 10.12
Kernel: 4.19.0-12-2-amd64
Build commit: 43085dc50
Build date: Fri Apr  8 09:04:48 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic02-005

Platform: x86_64-mlnx_msn4700-r0
HwSKU: ACS-MSN4700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2119X03331
Uptime: 16:45:09 up 43 min,  1 user,  load average: 0.72, 0.96, 0.79

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-syncd-mlnx             202012_rc.7-43085dc50_Internal   02b0fbbb5bd6        853MB
docker-syncd-mlnx             latest                           02b0fbbb5bd6        853MB
docker-platform-monitor       202012_rc.7-43085dc50_Internal   a9900e4f6bfb        665MB
docker-platform-monitor       latest                           a9900e4f6bfb        665MB
docker-snmp                   202012_rc.7-43085dc50_Internal   a923224abc11        406MB
docker-snmp                   latest                           a923224abc11        406MB
docker-teamd                  202012_rc.7-43085dc50_Internal   337f9f1b1e88        374MB
docker-teamd                  latest                           337f9f1b1e88        374MB
docker-orchagent              202012_rc.7-43085dc50_Internal   4302cc9fddf3        391MB
docker-orchagent              latest                           4302cc9fddf3        391MB
docker-nat                    202012_rc.7-43085dc50_Internal   e8256f5663ce        377MB
docker-nat                    latest                           e8256f5663ce        377MB
docker-fpm-frr                202012_rc.7-43085dc50_Internal   ce9537e8fd81        392MB
docker-fpm-frr                latest                           ce9537e8fd81        392MB
docker-sflow                  202012_rc.7-43085dc50_Internal   ddb6fbed6bd6        375MB
docker-sflow                  latest                           ddb6fbed6bd6        375MB
docker-router-advertiser      202012_rc.7-43085dc50_Internal   84be2aa68462        362MB
docker-router-advertiser      latest                           84be2aa68462        362MB
docker-database               202012_rc.7-43085dc50_Internal   bc95fad661d5        361MB
docker-database               latest                           bc95fad661d5        361MB
docker-lldp                   202012_rc.7-43085dc50_Internal   60b9c78e2de2        402MB
docker-lldp                   latest                           60b9c78e2de2        402MB
docker-dhcp-relay             202012_rc.7-43085dc50_Internal   fc40828e7820        375MB
docker-dhcp-relay             latest                           fc40828e7820        375MB
docker-sonic-telemetry        202012_rc.7-43085dc50_Internal   5301401f2127        451MB
docker-sonic-telemetry        latest                           5301401f2127        451MB
docker-sonic-mgmt-framework   202012_rc.7-43085dc50_Internal   48ece549e690        687MB
docker-sonic-mgmt-framework   latest                           48ece549e690        687MB
docker-mux                    202012_rc.7-43085dc50_Internal   ff233d40c665        414MB
docker-mux                    latest                           ff233d40c665        414MB

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sonic_dump_r-leopard-58_202012.tar.gz](https://github.com/Azure/sonic-buildimage/files/8508879/sonic_dump_r-leopard-58_202012.tar.gz)

**Comment by prsunny** [comment]
@volodymyrsamotiy working on the fix and verify if there is a feature gap.

**Comment by dgsudharsan** [comment]
This issue is closed by https://github.com/sonic-net/sonic-utilities/pull/2268
