### ISSUE TITLE
sonic-cli-gen  giver error

### ISSUE THREAD

**Issue by aslam-man** [sonic-net/sonic-buildimage#10741]
#### Description

Following command  is not generationg CLI , is giving error
root@ip-172-26-8-32:/# sonic-cli-gen generate config sonic-bgp-global.yang

#### Steps to reproduce the issue:
Run above command from sonic shell

#### Describe the results you received:
Gives following error
oot@ip-172-26-8-32:/# sonic-cli-gen generate config sonic-bgp-global.yang
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cli-gen", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sonic_cli_gen/main.py", line 36, in generat
e
    ctx.obj['gen'].generate_cli_plugin(cli_group, yang_mode
File "/usr/local/lib/python3.7/dist-packages/sonic_cli_gen/generator.py", line 46, in ge
nerate_cli_plugin
    yang_dict = parser.parse_yang_model()
  File "/usr/local/lib/python3.7/dist-packages/sonic_cli_gen/yang_parser.py", line 128, in
 parse_yang_model
    self._init_yang_module_and_containers()

#### Describe the results you expected:
CLI to be generated for given yang 

#### Output of `show version`:

```
/bin/sh: 1: sudo: not found

SONiC Software Version: SONiC.
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/main.py", line 1094, in version
    click.echo("Distribution: Debian {}".format(version_info['debian_version']))
KeyError: 'debian_version'
```
#### Output of `show techsupport`:

```
root@ip-172-26-8-32:/# show techsupport
/bin/sh: 1: sudo: not found
/bin/sh: 1: sudo: not found
```

**Comment by zhangyanzhao** [comment]
AppExtension related, need Nvidia team to take a look.

**Comment by vadymhlushko-mlnx** [comment]
Please try to execute the next CLI command:

`oot@ip-172-26-8-32:/# sonic-cli-gen generate config sonic-bgp-global`

As you may notice, you should provide the YANG model name without the `.yang` ending.

**Comment by volodymyrsamotiy** [comment]
As @vadymhlushko-mlnx replied need to use YANG model name without ".yang" extension in CLI.
After that it should work.
Closing this issue.
