### ISSUE TITLE
[PDDF]  API get_lpmode and set_lpmode don't work on QSFP port

### ISSUE THREAD

**Issue by jostar-yang** [sonic-net/sonic-buildimage#11785]
#### Description
API get_lpmode and set_lpmode don't work on QSFP port on pddf. PDDF base code call sfp_refactor to provide set_lpmode and get_lpmode. From fail information, it seems sonic_xcvr sfp_refactor doesn't suport lpmode function on QSFP port. 

#### Steps to reproduce the issue:
1.  Run python3 and import sonic_platform
2.  Insert to port55. 
Make sure  "platform_chassis.get_sfp(55).get_presence()" get True 
3. Input " platform_chassis.get_sfp(55).get_lpmode()"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform_pddf_base/pddf_sfp.py", line 198, in get_lpmode
    lpmode = super().get_lpmode()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 154, in get_lpmode
    return api.get_lpmode() if api is not None else None
AttributeError: 'Sff8436Api' object has no attribute 'get_lpmode'

#### Describe the results you received:

File "/usr/local/lib/python3.9/dist-packages/sonic_platform_pddf_base/pddf_sfp.py", line 198, in get_lpmode
    lpmode = super().get_lpmode()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 154, in get_lpmode
    return api.get_lpmode() if api is not None else None
AttributeError: 'Sff8436Api' object has no attribute 'get_lpmode'
#### Describe the results you expected:
platform_chassis.get_sfp(55).get_lpmode() , platform_chassis.get_sfp(55).set_lpmode(True) should work

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by FuzailBrcm** [comment]
I will look into it. Please assign it to me.

**Comment by FuzailBrcm** [comment]
Fix is in this PR.
https://github.com/sonic-net/sonic-buildimage/pull/11786
