### ISSUE TITLE
[reboot-cause] after couple times of fast-reboot or warm-reboot, the reboot cause would become unknown

### ISSUE THREAD

**Issue by WistronNetwork** [sonic-net/sonic-buildimage#11930]
#### Description

After couple times of fast-reboot or warm-reboot, the reboot cause would become "unknown", and determine-reboot-cause.service would be exited with failure.

#### Steps to reproduce the issue:
do the "warm-reboot" or "fast-reboot" couple times

#### Describe the results you received:

after reboot, determine-reboot-cause.service would be failure
```
Mar 21 17:19:52.850855 lab-3200k INFO determine-reboot-cause[7281]: Traceback (most recent call last):
Mar 21 17:19:52.850940 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 559, in connect
Mar 21 17:19:52.852022 lab-3200k INFO determine-reboot-cause[7281]:     sock = self._connect()
Mar 21 17:19:52.852085 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 615, in _connect
Mar 21 17:19:52.852293 lab-3200k INFO determine-reboot-cause[7281]:     raise err
Mar 21 17:19:52.852344 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 603, in _connect
Mar 21 17:19:52.852529 lab-3200k INFO determine-reboot-cause[7281]:     sock.connect(socket_address)
Mar 21 17:19:52.852594 lab-3200k INFO determine-reboot-cause[7281]: OSError: [Errno 101] Network is unreachable
Mar 21 17:19:52.852645 lab-3200k INFO determine-reboot-cause[7281]: During handling of the above exception, another exception occurred:
Mar 21 17:19:52.852695 lab-3200k INFO determine-reboot-cause[7281]: Traceback (most recent call last):
Mar 21 17:19:52.852740 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/bin/determine-reboot-cause", line 228, in <module>
Mar 21 17:19:52.852792 lab-3200k INFO determine-reboot-cause[7281]:     main()
Mar 21 17:19:52.852837 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/bin/determine-reboot-cause", line 189, in main
Mar 21 17:19:52.852890 lab-3200k INFO determine-reboot-cause[7281]:     previous_reboot_cause = find_hardware_reboot_cause()
Mar 21 17:19:52.852932 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/bin/determine-reboot-cause", line 119, in find_hardware_reboot_cause
Mar 21 17:19:52.852983 lab-3200k INFO determine-reboot-cause[7281]:     hardware_reboot_cause_major, hardware_reboot_cause_minor = get_reboot_cause_from_platform()
Mar 21 17:19:52.853023 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/bin/determine-reboot-cause", line 107, in get_reboot_cause_from_platform
Mar 21 17:19:52.853077 lab-3200k INFO determine-reboot-cause[7281]:     platform  = sonic_platform.platform.Platform()
Mar 21 17:19:52.853118 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/platform.py", line 20, in __init__
Mar 21 17:19:52.853277 lab-3200k INFO determine-reboot-cause[7281]:     self._chassis = Chassis()
Mar 21 17:19:52.853330 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 49, in __init__
Mar 21 17:19:52.853518 lab-3200k INFO determine-reboot-cause[7281]:     self.__initialize_eeprom()
Mar 21 17:19:52.853557 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 79, in __initialize_eeprom
Mar 21 17:19:52.853621 lab-3200k INFO determine-reboot-cause[7281]:     self._eeprom = Tlv()
Mar 21 17:19:52.853671 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/eeprom.py", line 33, in __init__
Mar 21 17:19:52.853954 lab-3200k INFO determine-reboot-cause[7281]:     self._eeprom = self._load_eeprom()
Mar 21 17:19:52.853989 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/eeprom.py", line 64, in _load_eeprom
Mar 21 17:19:52.854047 lab-3200k INFO determine-reboot-cause[7281]:     err = self.read_eeprom_db()
Mar 21 17:19:52.854083 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py", line 283, in read_eeprom_db
Mar 21 17:19:52.855515 lab-3200k INFO determine-reboot-cause[7281]:     db_state = self._redis_hget('EEPROM_INFO|State', 'Initialized')
Mar 21 17:19:52.855594 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py", line 630, in _redis_hget
Mar 21 17:19:52.855775 lab-3200k INFO determine-reboot-cause[7281]:     value = self.redis_client.hget(key, field)
Mar 21 17:19:52.855823 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 3010, in hget
Mar 21 17:19:52.857925 lab-3200k INFO determine-reboot-cause[7281]:     return self.execute_command('HGET', name, key)
Mar 21 17:19:52.858012 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 898, in execute_command
Mar 21 17:19:52.858323 lab-3200k INFO determine-reboot-cause[7281]:     conn = self.connection or pool.get_connection(command_name, **options)
Mar 21 17:19:52.858386 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1192, in get_connection
Mar 21 17:19:52.858738 lab-3200k INFO determine-reboot-cause[7281]:     connection.connect()
Mar 21 17:19:52.858822 lab-3200k INFO determine-reboot-cause[7281]:   File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 563, in connect
Mar 21 17:19:52.859019 lab-3200k INFO determine-reboot-cause[7281]:     raise ConnectionError(self._error_message(e))
Mar 21 17:19:52.859078 lab-3200k INFO determine-reboot-cause[7281]: redis.exceptions.ConnectionError: Error 101 connecting to localhost:6379. Network is unreachable.
Mar 21 17:19:52.886904 lab-3200k NOTICE systemd[1]: determine-reboot-cause.service: Main process exited, code=exited, status=1/FAILURE
Mar 21 17:19:52.887051 lab-3200k WARNING systemd[1]: determine-reboot-cause.service: Failed with result 'exit-code'.
```
and then process-reboot-cause would get "unknown" result.
```
Mar 21 17:21:27.860614 lab-3200k INFO process-reboot-cause: Starting up...
Mar 21 17:21:27.860723 lab-3200k INFO process-reboot-cause: Previous reboot cause: Unknown
Mar 21 17:21:27.876598 lab-3200k INFO systemd[1]: process-reboot-cause.service: Succeeded.
```
#### Describe the results you expected:
the determine-reboot-cause.service should NOT exited with failure, and the reboot cause should NOT be "unknown" 

#### Output of `show version`:

![image](https://user-images.githubusercontent.com/106370135/187851120-5327b318-c47a-4db6-a113-a8bacb998dfa.png)

#### Output of `show techsupport`:
N/A

**Comment by WistronNetwork** [comment]
@prgeor would you please check? any comment? thanks.

**Comment by WistronNetwork** [comment]
@prgeor could we have determine-reboot-cause.service auto-restart to recover this symptom?
