### ISSUE TITLE
radv docker: jinja2.exceptions.UndefinedError: 'vlan_list' is undefined

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#12031]
#### Description

 Following traceback is seen in docker logs for radv when VLAN_INTERFACE config is not present:

/usr/local/lib/python3.9/dist-packages/supervisor/[options.py:473](https://options.py:473/): UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
2022-03-20 19:57:36,977 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2022-03-20 19:57:36,978 INFO Set uid to user 0 succeeded
2022-03-20 19:57:36,983 INFO RPC interface 'supervisor' initialized
2022-03-20 19:57:36,983 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-03-20 19:57:36,984 INFO supervisord started with pid 1
2022-03-20 19:57:37,986 INFO spawned: 'dependent-startup' with pid 10
2022-03-20 19:57:37,988 INFO spawned: 'supervisor-proc-exit-script' with pid 11
2022-03-20 19:57:37,990 INFO spawned: 'start' with pid 12
2022-03-20 19:57:37,996 INFO success: start entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-20 19:57:37,996 INFO exited: start (exit status 0; expected)
2022-03-20 19:57:39,202 INFO success: dependent-startup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-20 19:57:39,202 INFO success: supervisor-proc-exit-script entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-20 19:57:39,206 INFO spawned: 'rsyslogd' with pid 13
2022-03-20 19:57:40,237 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-20 19:57:41,265 INFO exited: dependent-startup (exit status 0; expected)
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 445, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 409, in main
    template_data = template.render(data)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/[environment.py](https://environment.py/)", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/[environment.py](https://environment.py/)", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/share/sonic/templates/radvd.conf.j2", line 27, in top-level template code
    {% for name, prefixes in vlan_list.items() %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/[environment.py](https://environment.py/)", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'vlan_list' is undefined
chmod: cannot access '/usr/bin/wait_for_link.sh': No such file or directory

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
@abdosi FYI-

**Comment by prsunny** [comment]
@kellyyeh for viz

**Comment by abdosi** [comment]
@kellyyeh wondering can we enhance to to enable radv router based on device role ?

**Comment by anamehra** [comment]
The bug is in file https://github.com/sonic-net/sonic-buildimage/blob/master/dockers/docker-router-advertiser/radvd.conf.j2

12  {% if VLAN_INTERFACE %}
13  {% set vlan_list = dict() %}

The set statement to init vlan_list should be before if check. The current code fails at 
27  {% for name, prefixes in vlan_list.items() %}

when line 12 is false because vlan_list is never declared.

**Comment by prsunny** [comment]
> The bug is in file https://github.com/sonic-net/sonic-buildimage/blob/master/dockers/docker-router-advertiser/radvd.conf.j2
> 
> 12 {% if VLAN_INTERFACE %} 13 {% set vlan_list = dict() %}
> 
> The set statement to init vlan_list should be before if check. The current code fails at 27 {% for name, prefixes in vlan_list.items() %}
> 
> when line 12 is false because vlan_list is never declared.

@anamehra , could you provide the fix?
