### ISSUE TITLE
[202205][multiasic] after sonic-installer install a  new image, docke0 IP is changed and sudo reboot  command is hung. 

### ISSUE THREAD

**Issue by mlok-nokia** [sonic-net/sonic-buildimage#12049]
#### Description
On 202205 branch, after sonic-installer installed a new image on a multiasic platform, the interface docker0 IP 140.127.1.1 is changed to 172.18.0.1.  And the sudo reboot command is hung fro a long time and all Sonic commands produce a backtrace .  The same issue https://github.com/sonic-net/sonic-buildimage/issues/10135 has been fixed in the master.  It looks like PR  https://github.com/sonic-net/sonic-utilities/pull/2179 needs to be cherry pick to 202205 branch.

#### Steps to reproduce the issue:
1.  Run a show command like 'show feature status'
2. Run sonic-install install to install an new image that doesn't exit on the DUT.
3. Run the show command again.

#### Describe the results you received:
```
admin@sonic:~$ sudo sonic-installer install /tmp/sonic-broadcom-dnx.bin -y
Installing image SONiC-OS-HEAD.230935-dirty-20220301.182109 and setting it as default...
Command: bash /tmp/sonic_image
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in SONiC
ONIE Installer: platform: x86_64-broadcom-dnx-r0
onie_platform: x86_64-nokia_ixr7250e_sup-r0
Removing old SONiC installation /host/image-HEAD.231265-dirty-20220302.011117
Installing SONiC to /host/image-HEAD.230935-dirty-20220301.182109
.
.
.
```
```
admin@sonic:~$ show feature status
Traceback (most recent call last):
  File "/usr/local/bin/show", line 5, in <module>
    from show.main import cli
  File "/usr/local/lib/python3.9/dist-packages/show/main.py", line 8, in <module>
    import utilities_common.cli as clicommon
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/cli.py", line 189, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/cli.py", line 126, in __init__
    self.port_dict = multi_asic.get_port_table()
  File "/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py", line 295, in get_port_table
    ports = get_port_table_for_asic(ns)
  File "/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py", line 309, in get_port_table_for_asic
    config_db = connect_config_db_for_ns(namespace)
  File "/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py", line 43, in connect_config_db_for_ns
    config_db.connect()
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1829, in connect
    return _swsscommon.ConfigDBConnector_Native_connect(self, wait_for_init, retry_on)
RuntimeError: Unable to connect to redis: Cannot assign requested address
admin@sonic:~$
```
#### Describe the results you expected:
Should not have backtrace and commands should works fine.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
https://github.com/sonic-net/sonic-utilities/pull/2179 needs to be cherry pick to 202205 branch.

**Comment by rlhui** [comment]
@mlok-nokia fix should be in 202205 now, could you confirm if issue is fixed?
