### ISSUE TITLE
vnet_route_check Monit script fails when vnet routes are setup

### ISSUE THREAD

**Issue by antonptashnik** [sonic-net/sonic-buildimage#12070]
#### Description

vnet_route_check script used by Monit exits with the error below when there are any Vnet routes configured
```
Traceback (most recent call last):
  File "/usr/local/bin/vnet_route_check.py", line 359, in <module>
    sys.exit(main())
  File "/usr/local/bin/vnet_route_check.py", line 330, in main
    app_db_vnet_routes = get_vnet_routes_from_app_db()
  File "/usr/local/bin/vnet_route_check.py", line 222, in get_vnet_routes_from_app_db
    intf = vnet_intfs[vnet_name][0]
KeyError: 'Vnet_v4_in_v4-0'
```
Note there is a PR that was intended to address the issue but the issue is still present. The PR is https://github.com/sonic-net/sonic-utilities/pull/2268

#### Steps to reproduce the issue:
1. Save each config below to a JSON file and apply with `sudo config load filename.json`
```
{    
"VXLAN_TUNNEL": {"tunnel_v4": {"src_ip": "10.1.0.32"}}
}
```
```
{
"VNET": {
  "Vnet_v4_in_v4-0": {
    "vxlan_tunnel": "tunnel_v4",
    "scope": "default",
    "vni": "10000",
    "peer_list": ""
}}}
```
```
{
"INTERFACE": {
  "Ethernet240": {
    "vnet_name": "Vnet_v4_in_v4-0"
}}}
```

2. Run vnet_route_check script
```
/usr/local/bin/vnet_route_check.py
```

#### Describe the results you received:
```
Traceback (most recent call last):
  File "/usr/local/bin/vnet_route_check.py", line 359, in <module>
    sys.exit(main())
  File "/usr/local/bin/vnet_route_check.py", line 330, in main
    app_db_vnet_routes = get_vnet_routes_from_app_db()
  File "/usr/local/bin/vnet_route_check.py", line 222, in get_vnet_routes_from_app_db
    intf = vnet_intfs[vnet_name][0]
KeyError: 'Vnet_v4_in_v4-0'
```

#### Describe the results you expected:
Script finishes successfully with no interruption.

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.147826-dirty-20220913.162946
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: b34d94be1
Build date: Tue Sep 13 16:35:17 UTC 2022
Built by: AzDevOps@sonic-build-workers-0023BK

Platform: x86_64-accton_as9516_32d-r0
HwSKU: newport
ASIC: barefoot
ASIC Count: 1
Serial Number: AJ19049805
Model Number: NP5ZZ8632007A
Hardware Revision: N/A
Uptime: 13:56:33 up  2:06,  3 users,  load average: 0.34, 0.56, 0.54
Date: Wed 14 Sep 2022 13:56:33
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
@volodymyrsamotiy , can you please check?

**Comment by antonptashnik** [comment]
@zhangyanzhao I see you put "triaged" tag so I suppose the issue was investigated. Please provide any investigation results and URLs to pending fixes if present. Thanks in advance!

**Comment by volodymyrsamotiy** [comment]
I wasn't able to reproduce this issue on the image with the same hash (SONiC-OS-master.147814-b34d94be1).
I actually faced another error: "ValueError: Circular reference detected".
But I also tried on the latest image (SONiC-OS-master.162640-ef0559c03) and all looks working there.
Could you please check on latest image as well and confirm whether this issue is still reproducible in your case?

**Comment by prgeor** [comment]
@antonptashnik closing for now. please open if reproducible.
