### ISSUE TITLE
no PTF is built with SAI Thrift for py3 env

### ISSUE THREAD

**Issue by antonptashnik** [sonic-net/sonic-buildimage#12420]
#### Description
Recently QoS SAI test were migrated to Python 3 https://github.com/sonic-net/sonic-mgmt/pull/6363
Tests require Python SAI thrift lib to be installed in PTF but recent PTFs have the lib installed for Python 2 env only.
Moreover no bullseye sai thrift debs present among latest build artifacts.

#### Steps to reproduce the issue:

1. Install any recently built PTF
2. Login to PTF
3. Check SAI Thrift lib installation
```
root@d04ed46e05ec:~# pip3 list | grep thrif # py3 packages are not installed
root@d04ed46e05ec:~# pip list | grep thrif  # but py2 packages are installed
saithrift                          0.9
thrift                             0.11.0 
```

#### Describe the results you received:
saithrift is installed only for Python 2

#### Describe the results you expected:
saithrift is installed both for Python 2 and Python 3

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ZhaohuiS** [comment]
@antonptashnik 

The purpose of https://github.com/sonic-net/sonic-mgmt/pull/6363 is to fix the incompatibility of saithrift version and ptf version ran by test_qos_sai.

Since saithrift is upgraded into python3, we have to run env-python3/ptf in virtual environment in ptf container.
[https://github.com/sonic-net/sonic-mgmt/blob/master/tests/qos/qos_sai_base.py#:~:text=/root/env%2Dpython3/bin/ptf%22](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsonic-net%2Fsonic-mgmt%2Fblob%2Fmaster%2Ftests%2Fqos%2Fqos_sai_base.py%23%3A~%3Atext%3D%2Froot%2Fenv-python3%2Fbin%2Fptf%2522&data=05%7C01%7Czhaohuisun%40microsoft.com%7C094791e530b0432480dd08dab593bfdf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638021945121112483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FEqZd7klwionXTF9pGBE2Xr7EGnsAqZKfrVWZO4Pllg%3D&reserved=0) 
 
In ptf virtual environment, you will see saithrift and thrift are installed for python3.
 
If your saithrift is python2, please run test case against 202012 branch in sonic-mgmt repo, which is still uses python2 ptf.
 
This is saithrift for Mellanox master branch:
```
root@ac4b1b0974c3:~# dpkg -c python-saithrift_0.9.4_amd64.deb
drwxr-xr-x root/root         0 2017-03-24 22:23 ./
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/lib/
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/lib/python3/
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/lib/python3/dist-packages/
-rw-r--r-- root/root      1376 2017-03-24 22:23 ./usr/lib/python3/dist-packages/saithrift-0.9-py3.9.egg-info
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/
-rw-r--r-- root/root        52 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__init__.py
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__pycache__/
-rw-r--r-- root/root       246 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__pycache__/__init__.cpython-39.pyc
-rw-r--r-- root/root       498 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__pycache__/constants.cpython-39.pyc
-rw-r--r-- root/root    301274 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__pycache__/sai_headers.cpython-39.pyc
-rw-r--r-- root/root    617585 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__pycache__/switch_sai_rpc.cpython-39.pyc
-rw-r--r-- root/root     64823 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/__pycache__/ttypes.cpython-39.pyc
-rw-r--r-- root/root       366 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/constants.py
-rw-r--r-- root/root    612107 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/sai_headers.py
-rw-r--r-- root/root    785414 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/switch_sai_rpc.py
-rw-r--r-- root/root     90623 2017-03-24 22:23 ./usr/lib/python3/dist-packages/switch_sai_thrift/ttypes.py
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/share/
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/share/doc/
drwxr-xr-x root/root         0 2017-03-24 22:23 ./usr/share/doc/python-saithrift/
-rw-r--r-- root/root       146 2017-03-24 22:23 ./usr/share/doc/python-saithrift/changelog.gz
 
 
root@ac4b1b0974c3:~# source /root/env-python3/bin/activate
(env-python3) root@ac4b1b0974c3:~# pip list | grep thrift               
saithrift              0.9
thrift                 0.16.0
(env-python3) root@ac4b1b0974c3:~# pip --version
pip 22.3 from /root/env-python3/lib/python3.7/site-packages/pip (python 3.7)
```


BTW,  python-saithrift_0.9.4_amd64.deb is built out together with image and is installed in test_pretest.py.
[https://github.com/sonic-net/sonic-mgmt/blob/master/tests/test_pretest.py#:~:text=ptfhost.shell(%22dpkg%20%2Di%20%7B%7D%22.format(os.path.join(%22/root%22%2C%20pkg_name)))](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsonic-net%2Fsonic-mgmt%2Fblob%2Fmaster%2Ftests%2Ftest_pretest.py%23%3A~%3Atext%3Dptfhost.shell(%2522dpkg%2520-i%2520%257B%257D%2522.format(os.path.join(%2522%2Froot%2522%252C%2520pkg_name)))&data=05%7C01%7Czhaohuisun%40microsoft.com%7C094791e530b0432480dd08dab593bfdf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638021945120956255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h4itPG82Nf0GLkUyl2fTzPDPSkoMdbXBACaHy3jD874%3D&reserved=0)
 
If you want to run test_qos_sai.py, please make sure test_pretest.py is ran to success. 
Second option is you download it and install it manually. After the installation, you can use find it in the installed list.
 
 
Here is the commmand I used to run test_qos_sai.py:
`pytest qos/test_qos_sai.py --inventory ../ansible/str2,../ansible/veos --testbed testbed_name --testbed_file ../ansible/testbed.yaml --log-cli-level warning --log-file-level debug --skip_sanity --kube_master unset --showlocals --assert plain --show-capture no -rav --allow_recover --py_saithrift_url=http://10.10.10.10/installer/sonic/mellanox/public/python-saithrift_0.9.4_amd64.deb --completeness_level=confident --public_docker_registry`

Make sure `--py_saithrift_url` points to the deb file you can downloaded.

**Comment by ZhaohuiS** [comment]
@antonptashnik 
mellanox's saithrift is built for bullseye https://dev.azure.com/mssonic/build/_build/results?buildId=170542&view=logs&j=d37bc48d-29a0-534f-a1dc-3d699deb17a6&t=933dfdc6-d074-504d-ee66-71743fd9ae4e&l=2618

```
[ building ] [ target/debs/bullseye/libsaithrift-dev_0.9.4_amd64.deb ] 
[ finished ] [ target/debs/bullseye/libsaithrift-dev_0.9.4_amd64.deb ] 
[ building ] [ target/debs/bullseye/libsaithrift-dev_0.9.4_amd64.deb-install ] 
[ finished ] [ target/debs/bullseye/libsaithrift-dev_0.9.4_amd64.deb-install ] 
```


VS's saithrift is still built for buster, because docker-ptf has been upgrade to bullseye, it only has virtual py3 environment inside https://dev.azure.com/mssonic/build/_build/results?buildId=169710&view=logs&j=cef3d8a9-152e-5193-620b-567dc18af272&t=359769c4-8b5e-5976-a793-85da132e0a6f&l=3740

```
[ building ] [ target/debs/buster/libsaithrift-dev_0.9.4_amd64.deb ] 
[ finished ] [ target/debs/buster/libsaithrift-dev_0.9.4_amd64.deb ] 
[ building ] [ target/debs/buster/python-saithrift_0.9.4_amd64.deb ] 
[ finished ] [ target/debs/buster/python-saithrift_0.9.4_amd64.deb ] 
```


So whatever docker-ptf image is, it installs py2 saithrift deb file, I verified it:

```
root@47dd0a71ef89:/# find . -name "switch_sai_rpc.py"
./usr/lib/python2.7/dist-packages/switch_sai_thrift/switch_sai_rpc.py
```

**Comment by kandancs** [comment]
@antonptashnik,@ZhaohuiS,

Can you please share the steps to install SAI PTF python3 with 202111?

If you share all packages which needs to installed in both switch and linux server..it will help for me.

Thanks in advance.

**Comment by ZhaohuiS** [comment]
@kandancs 
There is a test case test_update_saithrift_ptf in tests/test_pretest.py.
It downloads python-saithrift_0.9.4_amd64.deb and use dpkg -i to install it in ptf container.

```
def test_update_saithrift_ptf(request, ptfhost):
    '''
    Install the correct python saithrift package on the ptf
    '''
    py_saithrift_url = request.config.getoption("--py_saithrift_url")
    if not py_saithrift_url:
        pytest.skip("No URL specified for python saithrift package")
    pkg_name = py_saithrift_url.split("/")[-1]
    ptfhost.shell("rm -f {}".format(pkg_name))
    result = ptfhost.get_url(url=py_saithrift_url, dest="/root", module_ignore_errors=True, timeout=60)
    if result["failed"] or "OK" not in result["msg"]:
        pytest.skip("Download failed/error while installing python saithrift package")
    ptfhost.shell("dpkg -i {}".format(os.path.join("/root", pkg_name)))
    logging.info("Python saithrift package installed successfully")
```

**Comment by kandancs** [comment]
Hi @ZhaohuiS ,

I need to run SAI PTF suite SAI/ptf/saiport.py for the platform which is creating the ports in Switch Init itself.

Can you please let me know how to run SAI/ptf/saiport.py for  platform which is creating the ports in Switch Init itself.

Thanks in advance

**Comment by rraghav-cisco** [comment]
@ZhaohuiS where can we get the latest python3-saithrift ? The above link is not built anymore.
Recently we are seeing this failure in qos-sai runs:
```
        if (res.is_failed or 'exception' in res) and not module_ignore_errors:
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           failed = True
E           changed = True
E           end = 2025-09-19 04:05:36.422656
E           cmd = /root/env-python3/bin/ptf --test-dir saitests/py3 sai_qos_tests.ReleaseAllPorts --platform-dir ptftests --qlen=10000 --platform remote -t 'router_mac='"'"'24:D5:E4:26:9E:2A'"'"';src_server='"'"'1.75.44.205:9092'"'"';port_map_file='"'"'/root/ptf_test_port_map.json'"'"';sonic_asic_type='"'"'cisco-8000'"'"';sonic_version='"'"'azure_msft_202405.30122-dirty-20250911.034812'"'"';src_dut_index=0;src_asic_index=0;dst_dut_index=1;dst_asic_index=0;dut_username='"'"'admin'"'"';dut_password='"'"'password'"'"';dst_server='"'"'1.75.44.206:9092'"'"';platform_asic='"'"'cisco-8000'"'"'' --debug info --log-file /tmp/sai_qos_tests.ReleaseAllPorts.log --socket-recv-size 16384 --test-case-timeout 1850  --disable-ipv6 --disable-vxlan --disable-geneve --disable-erspan --disable-mpls --disable-nvgre
E           delta = 0:00:00.488534
E           rc = 1
E           invocation = {'module_args': {'creates': None, 'executable': None, 'chdir': '/root', 'strip_empty_ends': True, '_raw_params': '/root/env-python3/bin/ptf --test-dir saitests/py3 sai_qos_tests.ReleaseAllPorts --platform-dir ptftests --qlen=10000 --platform remote -t \'router_mac=\'"\'"\'24:D5:E4:26:9E:2A\'"\'"\';src_server=\'"\'"\'1.75.44.205:9092\'"\'"\';port_map_file=\'"\'"\'/root/ptf_test_port_map.json\'"\'"\';sonic_asic_type=\'"\'"\'cisco-8000\'"\'"\';sonic_version=\'"\'"\'azure_msft_202405.30122-dirty-20250911.034812\'"\'"\';src_dut_index=0;src_asic_index=0;dst_dut_index=1;dst_asic_index=0;dut_username=\'"\'"\'admin\'"\'"\';dut_password=\'"\'"\'password\'"\'"\';dst_server=\'"\'"\'1.75.44.206:9092\'"\'"\';platform_asic=\'"\'"\'cisco-8000\'"\'"\'\' --debug info --log-file /tmp/sai_qos_tests.ReleaseAllPorts.log --socket-recv-size 16384 --test-case-timeout 1850  --disable-ipv6 --disable-vxlan --disable-geneve --disable-erspan --disable-mpls --disable-nvgre', 'removes': None, 'argv': None, 'warn': False, '_uses_shell': True, 'stdin_add_newline': True, 'stdin': None}}
E           start = 2025-09-19 04:05:35.934122
E           msg = non-zero return code
E           _ansible_no_log = None
E           stdout =
E           Using packet manipulation module: ptf.packet_scapystderr =
E           /root/env-python3/lib/python3.7/site-packages/scapy/config.py:542: CryptographyDeprecationWarning: Python 3.7 is no longer supported by the Python core team and support for it is deprecated in cryptography. A future release of cryptography will remove support for Python 3.7.
E             import cryptography
E           Traceback (most recent call last):
E             File "/root/env-python3/bin/ptf", line 718, in <module>
E               test_modules = load_test_modules(config)
E             File "/root/env-python3/bin/ptf", line 555, in load_test_modules
E               mod = import_module(root, modname)
E             File "/root/env-python3/bin/ptf", line 112, in import_module
E               return module_specs.loader.load_module()
E             File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
E             File "<frozen importlib._bootstrap_external>", line 907, in load_module
E             File "<frozen importlib._bootstrap_external>", line 732, in load_module
E             File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
E             File "<frozen importlib._bootstrap>", line 696, in _load
E             File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
E             File "<frozen importlib._bootstrap_external>", line 728, in exec_module
E             File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
E             File "saitests/py3/sai_base_test.py", line 33, in <module>
E               from switch import (sai_thrift_port_tx_enable,      # noqa E402
E             File "saitests/py3/switch.py", line 33, in <module>
E               from switch_sai_thrift.sai_headers import SAI_ACL_ENTRY_ATTR_ACTION_MIRROR_EGRESS,\
E           ImportError: cannot import name 'SAI_SWITCH_ATTR_CREDIT_WD' from 'switch_sai_thrift.sai_headers' (/usr/lib/python3/dist-packages/switch_sai_thrift/sai_headers.py)
```

Manually I could see the same:
```root@369eced8783f:~# python3
Python 3.7.3 (default, Mar 23 2024, 16:12:05)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import switch_sai_thrift
>>> print (switch_sai_thrift.__file__)
/usr/lib/python3/dist-packages/switch_sai_thrift/__init__.py
>>> from switch_sai_thrift.sai_headers import SAI_SWITCH_ATTR_CREDIT_WD
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SAI_SWITCH_ATTR_CREDIT_WD' from 'switch_sai_thrift.sai_headers' (/usr/lib/python3/dist-packages/switch_sai_thrift/sai_headers.py)
>>>
root@369eced8783f:~#
```
This happened in msft.202405 branch: https://github.com/Azure/sonic-mgmt.msft/blob/202405/tests/saitests/py3/switch.py

**Comment by ZhaohuiS** [comment]
@opcoder0 is it related to ptf container upgrade?
could you pls have a look?

**Comment by opcoder0** [comment]
Hi @ZhaohuiS - I see the msft.202405 branch is using the `docker-ptf:latest` tag here https://github.com/Azure/sonic-mgmt.msft/blob/202405/ansible/roles/vm_set/tasks/add_topo.yml#L10. 

This means it should pick up an image with python3-saithrift being installed https://github.com/sonic-net/sonic-buildimage/blob/master/dockers/docker-ptf/Dockerfile.j2#L346-L353. 

However migration to latest docker-ptf was fully tested on `master` and recommended for release branches > 202411. So I think it may be better to set the docker-ptf tag to branch specific value as it is done in 202405 here - https://github.com/sonic-net/sonic-mgmt/blob/202405/ansible/roles/vm_set/tasks/add_topo.yml#L10

**Comment by rraghav-cisco** [comment]
@opcoder0 : Is there a downloadable docker-ptf image with the newest sai-thrift, or even a downloadable saithrift debian somewhere ?

**Comment by opcoder0** [comment]
@rraghav-cisco I see the error now. The python-saithrift installed in the `docker-ptf:latest` is for Python 2.7 environment and it is not in the sys.path.

I have learnt that the Python 3 saithrift is being built for Mellanox - [download link](https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzk1MTA1Mi9hcnRpZmFjdE5hbWUvc29uaWMtYnVpbGRpbWFnZS5tZWxsYW5veA2/content?format=file&subPath=%2Ftarget%2Fdebs%2Fbookworm%2Fpython-saithrift_0.9.4_amd64.deb)

I will raise a PR to include this one in the `docker-ptf:latest`
