### ISSUE TITLE
[memory_checker]Memory checker tracebacks when memory threshold is crossed

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#12794]
#### Description

Memory checker tracebacks when threshold is crossed. Below is the traceback seen. This issue is observed after the PR https://github.com/sonic-net/sonic-buildimage/pull/12563
This results in monit not restarting the container when memory threshold is more than configured value. This also results in https://github.com/sonic-net/sonic-mgmt/blob/master/tests/memory_checker/test_memory_checker.py failing in master

/usr/bin/memory_checker telemetry 400000
[telemetry]: Memory usage (760951603.2 Bytes) is larger than the threshold (400000 Bytes)!
Traceback (most recent call last):
  File "/usr/bin/memory_checker", line 173, in <module>
    main()
  File "/usr/bin/memory_checker", line 165, in main
    check_memory_usage(events_handle, args.container_name, args.threshold_value)
  File "/usr/bin/memory_checker", line 103, in check_memory_usage
    publish_events(events_handle, container_name, mem_usage_bytes, threshold_value)
  File "/usr/bin/memory_checker", line 64, in publish_events
    params["mem_usage"] = mem_usage_bytes
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 419, in __setitem__
    return _swsscommon.FieldValueMap___setitem__(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'FieldValueMap___setitem__'.
  Possible C/C++ prototypes are:
    std::map< std::string,std::string >::__setitem__(std::map< std::string,std::string >::key_type const &)
    std::map< std::string,std::string >::__setitem__(std::map< std::string,std::string >::key_type const &,std::map< std::string,std::string >::mapped_type const &)

#### Steps to reproduce the issue:
1. Run memory checker on a dockers with small threshold value
2.
3.

#### Output of `show version`:

```
SONiC Software Version: SONiC.kernel_upgrade.2-b6c203671_Internal
Distribution: Debian 11.5
Kernel: 5.10.0-18-2-amd64
Build commit: b6c203671
Build date: Fri Nov 11 03:38:41 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic-ci03-242

Platform: x86_64-mlnx_msn4410-r0
HwSKU: ACS-MSN4410
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2039X06760
Model Number: MSN4410-WS2FO
Hardware Revision: A1
Uptime: 16:18:46 up  7:19,  1 user,  load average: 1.78, 1.73, 2.09
Date: Thu 17 Nov 2022 16:18:46

Docker images:
REPOSITORY                    TAG                                   IMAGE ID       SIZE
docker-fpm-frr                kernel_upgrade.2-b6c203671_Internal   e7df33ff09af   536MB
docker-fpm-frr                latest                                e7df33ff09af   536MB
docker-orchagent              kernel_upgrade.2-b6c203671_Internal   2bf3c99e4f70   525MB
docker-orchagent              latest                                2bf3c99e4f70   525MB
docker-teamd                  kernel_upgrade.2-b6c203671_Internal   3a4be50e567a   506MB
docker-teamd                  latest                                3a4be50e567a   506MB
docker-sonic-telemetry        kernel_upgrade.2-b6c203671_Internal   abf5a49ad53d   784MB
docker-sonic-telemetry        latest                                abf5a49ad53d   784MB
docker-snmp                   kernel_upgrade.2-b6c203671_Internal   4d81188e6230   536MB
docker-snmp                   latest                                4d81188e6230   536MB
docker-macsec                 latest                                4c4ec94006a5   508MB
docker-dhcp-relay             latest                                d5a9d6a6ba7c   499MB
docker-eventd                 kernel_upgrade.2-b6c203671_Internal   88fe391c23d6   490MB
docker-eventd                 latest                                88fe391c23d6   490MB
docker-lldp                   kernel_upgrade.2-b6c203671_Internal   b4ecab569cfe   532MB
docker-lldp                   latest                                b4ecab569cfe   532MB
docker-database               kernel_upgrade.2-b6c203671_Internal   dd95c7ab515a   490MB
docker-database               latest                                dd95c7ab515a   490MB
docker-sonic-p4rt             kernel_upgrade.2-b6c203671_Internal   077e7fed7a2c   572MB
docker-sonic-p4rt             latest                                077e7fed7a2c   572MB
docker-mux                    kernel_upgrade.2-b6c203671_Internal   808e37230a85   538MB
docker-mux                    latest                                808e37230a85   538MB
docker-router-advertiser      kernel_upgrade.2-b6c203671_Internal   81e55b296563   490MB
docker-router-advertiser      latest                                81e55b296563   490MB
docker-sonic-mgmt-framework   kernel_upgrade.2-b6c203671_Internal   5ed166142465   610MB
docker-sonic-mgmt-framework   latest                                5ed166142465   610MB
docker-nat                    kernel_upgrade.2-b6c203671_Internal   9e45499624c9   479MB
docker-nat                    latest                                9e45499624c9   479MB
docker-sflow                  kernel_upgrade.2-b6c203671_Internal   7964fb9d052d   477MB
docker-sflow                  latest                                7964fb9d052d   477MB
docker-platform-monitor       kernel_upgrade.2-b6c203671_Internal   5a7b85d36b00   913MB
docker-platform-monitor       latest                                5a7b85d36b00   913MB
docker-syncd-mlnx             kernel_upgrade.2-b6c203671_Internal   cef14c37877f   906MB
docker-syncd-mlnx             latest                                cef14c37877f   906MB
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zbud-msft** [comment]
Fixed as part of https://github.com/sonic-net/sonic-buildimage/pull/12797
