### ISSUE TITLE
ERROR [internal] load metadata for docker.io/library/sonic-slave-buster:f7dd6627837

### ISSUE THREAD

**Issue by yueyihui** [sonic-net/sonic-buildimage#13174]
#### Steps to reproduce the issue:
1. git clone --recurse-submodules https://github.com/sonic-net/sonic-buildimage.git
2. git checkout d6ee7f08c
3. make init
4. make configure PLATFORM=vs

#### Describe the results you received:
```
Step 22/80 : RUN pip3 install --upgrade pip
 ---> Running in ee1b9bcea6d7
Collecting pip
  Downloading https://files.pythonhosted.org/packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl (2.1MB)
[91mException:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.24.1-py2.py3-none-any.whl/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/share/python-wheels/urllib3-1.24.1-py2.py3-none-any.whl/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

#### Describe the results you expected:
pip2 and pip3 should be upgrade as expectation

**Comment by yueyihui** [comment]
it is a network issue
