### ISSUE TITLE
cannot import name 'platform_ndk_pb2' from 'platform_ndk' 

### ISSUE THREAD

**Issue by nagasomarowthu36** [sonic-net/sonic-buildimage#13851]
ImportError: cannot import name 'platform_ndk_pb2' from 'platform_ndk' (/usr/local/lib/python3.7/dist-packages/platform_ndk/init.py)

/usr/local/lib/python3.7/dist-packages/platform_ndk/nokia_common.py(16)()
-> from platform_ndk import platform_ndk_pb2

platform_ndk_pb2 module is missing from package https://github.com/nokia/sonic-platform/tree/main/chassis/platform_ndk.

Steps to reproduce the issue:
execute show interface status <interface-name> which doesn't have physical connection from sonic-cli docker and trace the failure in handler function.

root@sonic:/# show interface transceiver presence Ethernet3
Port       Presence
---------  ----------
Ethernet3  Present
root@sonic:/# show interface status Ethernet3
  Interface    Lanes    Speed    MTU    FEC     Alias    Vlan    Oper    Admin            Type    Asym PFC
-----------  -------  -------  -----  -----  --------  ------  ------  -------  --------------  ----------
  Ethernet3       11     9.8G   1500   none  fpCpri-3   trunk    down     down  SFP/SFP+/SFP28         N/A
root@sonic:/# show interface transceiver presence Ethernet4
Port       Presence
---------  -----------
Ethernet4  Not present
root@sonic:/# show interface status Ethernet4
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/module.py", line 12, in <module>
    from platform_ndk import nokia_common
  File "/usr/local/lib/python3.7/dist-packages/platform_ndk/nokia_common.py", line 14, in <module>
    from platform_ndk import platform_ndk_pb2
ImportError: cannot import name 'platform_ndk_pb2' from 'platform_ndk' (/usr/local/lib/python3.7/dist-packages/platform_ndk/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/chassis.py", line 13, in <module>
    from sonic_platform.module import Module
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/module.py", line 17, in <module>
    raise ImportError(str(e) + "- required module not found")
ImportError: cannot import name 'platform_ndk_pb2' from 'platform_ndk' (/usr/local/lib/python3.7/dist-packages/platform_ndk/__init__.py)- required module not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/platform.py", line 22, in __init__
    from sonic_platform.chassis import Chassis
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/chassis.py", line 26, in <module>
    raise ImportError(str(e) + "- required module not found")
ImportError: cannot import name 'platform_ndk_pb2' from 'platform_ndk' (/usr/local/lib/python3.7/dist-packages/platform_ndk/__init__.py)- required module not found- required module not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/intfutil", line 849, in <module>
    main()
  File "/usr/local/bin/intfutil", line 832, in main
    interface_stat.display_intf_status()
  File "/usr/local/bin/intfutil", line 459, in display_intf_status
    self.get_intf_status()
  File "/usr/local/lib/python3.7/dist-packages/utilities_common/multi_asic.py", line 151, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/intfutil", line 546, in get_intf_status
    self.table += self.generate_intf_status()
  File "/usr/local/bin/intfutil", line 497, in generate_intf_status
    port_optics_get(self.db, key, PORT_OPTICS_TYPE),
  File "/usr/local/bin/intfutil", line 230, in port_optics_get
    if is_rj45_port(intf_name):
  File "/usr/local/lib/python3.7/dist-packages/utilities_common/platform_sfputil_helper.py", line 117, in is_rj45_port
    platform_chassis = sonic_platform.platform.Platform().get_chassis()
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform/platform.py", line 24, in __init__
    raise ImportError("%s - required module not found" % e)
ImportError: cannot import name 'platform_ndk_pb2' from 'platform_ndk' (/usr/local/lib/python3.7/dist-packages/platform_ndk/__init__.py)- required module not found- required module not found - required module not found
root@sonic:/#

reproduction is not required as python module is missing from package(https://github.com/nokia/sonic-platform/tree/main/chassis/platform_ndk).

**Comment by mlok-nokia** [comment]
@nagasomarowthu36   Hi, Since the Issue doesn't have the "show platform version".  I assume you are using Nokia-IXR7250E chassis.  Based on the information which you provided, it looks like you are using the master image.   The master image cannot be run on Nokia-IXR7250E chassis.  The master branch doesn't have the nokia_platform_ndk debian package.  If you are using master image, it is expected.  Only 202205 branch image supports Nokia-IXR7250E chassis.

**Comment by judyjoseph** [comment]
Closing this as Nokia image is available from **[https://github.com/Azure/sonic-buildimage-msft]** branches.
