### ISSUE TITLE
IMP: Transciever "Not detected " but presence shown in "sudo sfputil show presence"

### ISSUE THREAD

**Issue by akash1mar** [sonic-net/sonic-buildimage#13937]
#### Description
I am facing issue in detecting the transciever . If I provide the command **"show interfaces transceiver presence"** it does not detect . But if i provide the "sudo sfputil show presence" then it gives detects transciever.
I can see continuous message from the syslog as below:

"Sep 19 10:43:48.250437 sonic INFO pmon#supervisord: xcvrd Error: unable to access file: [Errno 2] No such file or directory: '/sys/bus/i2c/devices/21-0062/module_present_17'"

I checked the i2c driver files "sudo ls /sys/bus/i2c/devices/".

admin@sonic:~$ sudo ls /sys/bus/i2c/devices/
0-0057   2-0073   31-0053  40-0053  49-0053  58-0053  i2c-22  i2c-39  i2c-55
0-0065   2-0074   32-0050  41-0050  50-0050  9-0050   i2c-23  i2c-4   i2c-56
0-0077   2-0075   32-0053  41-0053  50-0053  9-0058   i2c-24  i2c-40  i2c-57
10-0051  2-0076   33-0050  42-0050  51-0050  i2c-0    i2c-25  i2c-41  i2c-58
10-0059  21-0062  33-0053  42-0053  51-0053  i2c-1    i2c-26  i2c-42  i2c-59
1-0072   25-0050  34-0050  43-0050  52-0050  i2c-10   i2c-27  i2c-43  i2c-6
1-0076   25-0053  34-0053  43-0053  52-0053  i2c-11   i2c-28  i2c-44  i2c-60
17-0066  26-0050  35-0050  44-0050  53-0050  i2c-12   i2c-29  i2c-45  i2c-61
18-0048  26-0053  35-0053  44-0053  53-0053  i2c-13   i2c-3   i2c-46  i2c-62
18-0049  27-0050  36-0050  45-0050  54-0050  i2c-14   i2c-30  i2c-47  i2c-63
18-004a  27-0053  36-0053  45-0053  54-0053  i2c-15   i2c-31  i2c-48  i2c-64
18-004b  28-0050  37-0050  46-0050  55-0050  i2c-16   i2c-32  i2c-49  i2c-7
18-004c  28-0053  37-0053  46-0053  55-0053  i2c-17   i2c-33  i2c-5   i2c-8
18-004e  29-0050  38-0050  47-0050  56-0050  i2c-18   i2c-34  i2c-50  i2c-9
18-004f  29-0053  38-0053  47-0053  56-0053  i2c-19   i2c-35  i2c-51
19-0060  30-0050  39-0050  48-0050  57-0050  i2c-2    i2c-36  i2c-52
20-0061  30-0053  39-0053  48-0053  57-0053  i2c-20   i2c-37  i2c-53
2-0072   31-0050  40-0050  49-0050  58-0050  i2c-21   i2c-38  i2c-54

Issue is seen randomly , Not sure how it is able to work for one command and not for other . Is it related to any sequence order during boot time. Could you please help here in resolving the issue.

#### Steps to reproduce the issue:
1. Reboot the system with sonic build
2. Display the transciever details 
3. Display the syslog messages

#### Describe the results you received:
Transceiver "Not Detected"

#### Describe the results you expected:
Transciever should be detected with "show interfaces transceiver presence" command and we should have any syslog messages as mentioned above.

#### Output of `show version`:
admin@sonic:~$ show version

SONiC Software Version: SONiC.dev-sonic.77-dirty-20230209.013734
Distribution: Debian 11.6
Kernel: 5.10.0-12-2-amd64
Build commit: 8bf0e1b69
Build date: Wed Feb  8 23:19:07 UTC 2023
Built by: build@build-KVM

Platform: x86_64-accton_as9716_32d-r0
HwSKU: Accton-AS9716-32D
ASIC: broadcom
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 01:58:50 up 11:46,  1 user,  load average: 0.19, 0.31, 0.34
Date: Tue 20 Sep 2022 01:58:50

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```
[sonic_dump_sonic_20220920_014458.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/10807449/sonic_dump_sonic_20220920_014458.tar.gz)

#### Additional information you deem important (e.g. issue happens only occasionally):

The issues happens in random manner. 

####
Logs
####

admin@sonic:~$ sudo sfputil show eeprom -p
Error: -p option requires an argument
admin@sonic:~$ sudo sfputil show eeprom
Ethernet64: SFP EEPROM detected
        Application Advertisement: N/A
        Connector: No separable connector
        Encoding: Unspecified
        Extended Identifier: Power Class 1 Module (1.5W max. Power consumption), No CLEI code present in Page 02h, No CDR in TX, No CDR in RX
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+ or later with SFF-8636 or SFF-8436
        Length Cable Assembly(m): 3.0
        Nominal Bit Rate(100Mbs): 0
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-CR4
                Fibre Channel Link Length: Medium (M)
                Fibre Channel Speed: Unknown
                Fibre Channel Transmission Media: Twin Axial Pair (TW)
                Fibre Channel Transmitter Technology: Unknown
                Gigabit Ethernet Compliant Codes: Unknown
                SAS/SATA Compliance Codes: Unknown
                SONET Compliance Codes: Unknown
        Vendor Date Code(YYYY-MM-DD Lot): 2013-08-22
        Vendor Name: Molex Inc.
        Vendor OUI: 00-09-3a
        Vendor PN: 1110409179
        Vendor Rev: A
        Vendor SN: 323430011

Ethernet248: SFP EEPROM not detected

Ethernet160: SFP EEPROM not detected

Ethernet88: SFP EEPROM not detected

Ethernet40: SFP EEPROM not detected

Ethernet72: SFP EEPROM not detected

Ethernet216: SFP EEPROM not detected

Ethernet192: SFP EEPROM not detected

Ethernet112: SFP EEPROM not detected

Ethernet32: SFP EEPROM not detected

Ethernet232: SFP EEPROM not detected

Ethernet8: SFP EEPROM not detected

Ethernet176: SFP EEPROM not detected

Ethernet80: SFP EEPROM not detected

Ethernet240: SFP EEPROM not detected

Ethernet0: SFP EEPROM not detected

Ethernet56: SFP EEPROM detected
        Active App Selection Host Lane 1: 1
        Active App Selection Host Lane 2: 1
        Active App Selection Host Lane 3: 1
        Active App Selection Host Lane 4: 1
        Active App Selection Host Lane 5: 1
        Active App Selection Host Lane 6: 1
        Active App Selection Host Lane 7: 1
        Active App Selection Host Lane 8: 1
        Active Firmware Version: 0.0
        Application Advertisement: {1: {'host_electrical_interface_id': '400GAUI-8 C2M (Annex 120E)', 'module_media_interface_id': '400GBASE-SR8 (Clause 138)', 'media_lane_count': 8, 'host_lane_count': 8, 'host_lane_assignment_options': 1}}
        CMIS Revision: 4.0
        Connector: MPO 1x16
        Encoding: N/A
        Extended Identifier: Power Class 6 (11.0W Max)
        Extended RateSelect Compliance: N/A
        Hardware Revision: 1.1
        Host Electrical Interface: 400GAUI-8 C2M (Annex 120E)
        Host Lane Assignment Options: 1
        Host Lane Count: 8
        Identifier: QSFP-DD Double Density 8X Pluggable Transceiver
        Inactive Firmware Version: 1.0
        Length Cable Assembly(m): 0.0
        Media Interface Code: 400GBASE-SR8 (Clause 138)
        Media Interface Technology: 850 nm VCSEL
        Media Lane Assignment Options: 1
        Media Lane Count: 8
        Nominal Bit Rate(100Mbs): 0
        Specification compliance: nm_850_media_interface
        Vendor Date Code(YYYY-MM-DD Lot): 2022-04-06
        Vendor Name: E.C.I. NETWORKS
        Vendor OUI: da-28-ec
        Vendor PN: EN-QDD-SR8
        Vendor Rev: 10
        Vendor SN: 7000007300001

Ethernet120: SFP EEPROM not detected

Ethernet48: SFP EEPROM not detected

Ethernet96: SFP EEPROM not detected

Ethernet16: SFP EEPROM not detected

Ethernet208: SFP EEPROM not detected

Ethernet152: SFP EEPROM not detected

Ethernet200: SFP EEPROM not detected

Ethernet128: SFP EEPROM not detected

Ethernet104: SFP EEPROM not detected

Ethernet168: SFP EEPROM not detected

Ethernet24: SFP EEPROM detected
        Application Advertisement: N/A
        Connector: No separable connector
        Encoding: Unspecified
        Extended Identifier: Power Class 1 Module (1.5W max.), No CLEI code present in Page 02h, No CDR in TX, No CDR in RX
        Extended RateSelect Compliance: Unknown
        Identifier: QSFP28 or later
        Length Cable Assembly(m): 3.0
        Nominal Bit Rate(100Mbs): 255
        Specification compliance:
                10/40G Ethernet Compliance Code: Extended
                Extended Specification Compliance: 100GBASE-CR4, 25GBASE-CR CA-25G-L or 50GBASE-CR2 with RS
                Fibre Channel Link Length: Unknown
                Fibre Channel Speed: Unknown
                Fibre Channel Transmission Media: Twin Axial Pair (TW)
                Fibre Channel Transmitter Technology: Unknown
                Gigabit Ethernet Compliant Codes: Unknown
                SAS/SATA Compliance Codes: Unknown
                SONET Compliance Codes: Unknown
        Vendor Date Code(YYYY-MM-DD Lot): 2022-11-13
        Vendor Name: OEM
        Vendor OUI: 00-00-00
        Vendor PN: QSFP28-100G-PCU3
        Vendor Rev: E
        Vendor SN: SY2211-LEH00001

Ethernet184: SFP EEPROM not detected

Ethernet144: SFP EEPROM not detected

Ethernet136: SFP EEPROM not detected

Ethernet224: SFP EEPROM not detected

admin@sonic:~$
admin@sonic:~$ sudo sfputil show presence
Port         Presence
-----------  -----------
Ethernet0    Not present
Ethernet8    Not present
Ethernet16   Not present
Ethernet24   Present
Ethernet32   Not present
Ethernet40   Not present
Ethernet48   Not present
Ethernet56   Present
Ethernet64   Present
Ethernet72   Not present
Ethernet80   Not present
Ethernet88   Not present
Ethernet96   Not present
Ethernet104  Not present
Ethernet112  Not present
Ethernet120  Not present
Ethernet128  Not present
Ethernet136  Not present
Ethernet144  Not present
Ethernet152  Not present
Ethernet160  Not present
Ethernet168  Not present
Ethernet176  Not present
Ethernet184  Not present
Ethernet192  Not present
Ethernet200  Not present
Ethernet208  Not present
Ethernet216  Not present
Ethernet224  Not present
Ethernet232  Not present
Ethernet240  Not present
Ethernet248  Not present
admin@sonic:~$ show interfaces transceiver presence
Port         Presence
-----------  -----------
Ethernet0    Not present
Ethernet8    Not present
Ethernet16   Not present
Ethernet24   Not present
Ethernet32   Not present
Ethernet40   Not present
Ethernet48   Not present
Ethernet56   Not present
Ethernet64   Not present
Ethernet72   Not present
Ethernet80   Not present
Ethernet88   Not present
Ethernet96   Not present
Ethernet104  Not present
Ethernet112  Not present
Ethernet120  Not present
Ethernet128  Not present
Ethernet136  Not present
Ethernet144  Not present
Ethernet152  Not present
Ethernet160  Not present
Ethernet168  Not present
Ethernet176  Not present
Ethernet184  Not present
Ethernet192  Not present
Ethernet200  Not present
Ethernet208  Not present
Ethernet216  Not present
Ethernet224  Not present
Ethernet232  Not present
Ethernet240  Not present
Ethernet248  Not present
admin@sonic:~$  show in transceiver eeprom Ethernet56 -d
Unable to initialize syseeprom - RuntimeError('PddfEeprom is not Programmed')Ethernet56: SFP EEPROM Not detected
admin@sonic:~$  show in transceiver eeprom Ethernet54 -d
Unable to initialize syseeprom - RuntimeError('PddfEeprom is not Programmed')Ethernet54: SFP EEPROM Not detected

**Comment by FuzailBrcm** [comment]
Looks like some issue with the sonic_platform python package import in PMON docker.

```
Sep 19 14:14:46.959922 sonic INFO pmon#supervisord 2022-09-19 14:14:46,959 INFO success: lm-sensors entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Sep 19 14:14:46.965908 sonic INFO pmon#supervisord 2022-09-19 14:14:46,965 INFO spawned: 'xcvrd' with pid 23
Sep 19 14:14:46.973163 sonic INFO pmon#supervisord 2022-09-19 14:14:46,972 INFO spawned: 'psud' with pid 25
Sep 19 14:14:46.981192 sonic INFO pmon#supervisord 2022-09-19 14:14:46,980 INFO spawned: 'syseepromd' with pid 26
Sep 19 14:14:46.989628 sonic INFO pmon#supervisord 2022-09-19 14:14:46,988 INFO spawned: 'thermalctld' with pid 28
Sep 19 14:14:47.071741 sonic INFO pmon#supervisord: psud Traceback (most recent call last):
Sep 19 14:14:47.075783 sonic INFO pmon#supervisord: psud   File "/usr/local/bin/psud", line 17, in <module>
Sep 19 14:14:47.075838 sonic INFO pmon#supervisord: psud     from sonic_platform.psu import Psu
Sep 19 14:14:47.075866 sonic INFO pmon#supervisord: psud ModuleNotFoundError: No module named 'sonic_platform.psu'
Sep 19 14:14:47.076342 sonic INFO pmon#supervisord 2022-09-19 14:14:47,075 INFO exited: psud (exit status 1; not expected)
Sep 19 14:14:47.131842 sonic ERR pmon#chassis_db_init: Failed to load chassis due to ModuleNotFoundError("No module named 'sonic_platform.platform'")
Sep 19 14:14:47.154853 sonic INFO pmon#supervisord 2022-09-19 14:14:47,152 INFO exited: chassis_db_init (exit status 1; not expected)
Sep 19 14:14:47.170761 sonic WARNING pmon#syseepromd[26]: Failed to load platform-specific eeprom from sonic_platform package due to AttributeError("module 'sonic_platform' has no attribute 'platform'"). Trying deprecated plugin method ...
Sep 19 14:14:47.199096 sonic INFO hostcfgd: Systemd configuration files are reloaded!
Sep 19 14:14:47.205244 sonic INFO pmon#supervisord: lm-sensors Starting sensor daemon: sensord
Sep 19 14:14:47.228024 sonic INFO pmon#supervisord: thermalctld Traceback (most recent call last):
Sep 19 14:14:47.228332 sonic INFO pmon#supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 932, in <module>
Sep 19 14:14:47.228386 sonic INFO pmon#supervisord: thermalctld     sys.exit(main())
Sep 19 14:14:47.228415 sonic INFO pmon#supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 917, in main
Sep 19 14:14:47.228456 sonic INFO pmon#supervisord: thermalctld     thermal_control = ThermalControlDaemon()
Sep 19 14:14:47.228488 sonic INFO pmon#supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 826, in __init__
Sep 19 14:14:47.228542 sonic INFO pmon#supervisord: thermalctld     self.chassis = sonic_platform.platform.Platform().get_chassis()
Sep 19 14:14:47.228542 sonic INFO pmon#supervisord: thermalctld AttributeError: module 'sonic_platform' has no attribute 'platform'
```

Although the pkg installation via pip3 install successfully completed on HOST. 
```
Sep 19 14:13:19 sonic pddf_util.py[844]: Failed :pip3 show sonic-platform > /dev/null 2>&1
Sep 19 14:13:19 sonic pddf_util.py[844]: Attemting to install the PDDF sonic_platform wheel package ...
Sep 19 14:13:19 sonic pddf_util.py[844]: Successfully installed /usr/share/sonic/device/x86_64-accton_as9716_32d-r0/sonic_platform-1.0-py3-none-any.whl package
Sep 19 14:13:19 sonic pddf_util.py[844]: Successfully installed /usr/share/sonic/device/x86_64-accton_as9716_32d-r0/sonic_platform-1.0-py3-none-any.whl package
```

Need to load the exact image on AS9716 platform and investigate.
@jostar-yang Can you look into this?

**Comment by jostar-yang** [comment]
From log,
psud ModuleNotFoundError: No module named 'sonic_platform.psu'
It seems sonic_platoform is not installed. But from another log, Successfully installed /usr/share/sonic/device/x86_64-accton_as9716_32d-r0/sonic_platform-1.0-py3-none-any.whl package.
Sonic_platform is installed. It is strange. I need to load image to check it.

**Comment by judyjoseph** [comment]
@akash1mar Could you check if this is still an issue ?

**Comment by jardel-lucca-venko** [comment]
@jostar-yang, @judyjoseph any idea on what `Unable to initialize syseeprom - RuntimeError('PddfEeprom is not Programmed')` means? I've seem this message in a device as well.

**Comment by f-agnes** [comment]
@jardel-lucca-venko I get the same message `Unable to initialize syseeprom - RuntimeError('PddfEeprom is not Programmed')` when I run the command `show interface status`. This message is displayed because the user admin cannot open the system EEPROM file (For Edgecore-7326 is /sys/bus/i2c/devices/i2c-0/0-0057/eeprom). If I run the command as sudo the message is not displayed. Eg `sudo show interface status`

**Comment by jardel-lucca-venko** [comment]
> @jardel-lucca-venko I get the same message `Unable to initialize syseeprom - RuntimeError('PddfEeprom is not Programmed')` when I run the command `show interface status`. This message is displayed because the user admin cannot open the system EEPROM file (For Edgecore-7326 is /sys/bus/i2c/devices/i2c-0/0-0057/eeprom). If I run the command as sudo the message is not displayed. Eg `sudo show interface status`

Thanks!
