### ISSUE TITLE
[system_health, test_device_checker] | Mocked valid fan speed, but it still reports invalid one: "fan1 speed is out of range, speed=20.0, range=[30.0,90.0]"

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#14209]
#### Description

Healthd check system status every 60 seconds. However, running checker may take several seconds. Say checker takes X seconds, healthd takes (60 + X) seconds to finish one iteration. This implementation makes sonic-mgmt test case not so stable because the value X is hard to predict and different among different platforms. It potentially causes test_device_checker case failed intermittently. 

A PR to fix it is: https://github.com/sonic-net/sonic-buildimage/pull/14085

#### Steps to reproduce the issue:
1. Run sonic-mgmt test case test_system_health.py::test_device_checker

#### Describe the results you received:
```
18:02:29 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest 
    self.ihook.pytest_pyfunc_call(pyfuncitem=self) 
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__ 
    return self._hookexec(self, self.get_hookimpls(), kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec 
    return self._inner_hookexec(hook, methods, kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda> 
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False, 
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall 
    return outcome.get_result() 
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result 
    _reraise(*ex)  # noqa 
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall 
    res = hook_impl.function(*args) 
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call 
    testfunction(**testargs) 
  File "/root/mars/workspace/sonic-mgmt/tests/system_health/test_system_health.py", line 184, in test_device_checker 
    assert not value or fan_expect_value not in value, 'Mock fan valid speed, expect {}, but it still report invalid speed' 
AssertionError: Mock fan valid speed, expect {}, but it still report invalid speed 
```

#### Describe the results you expected:
No error observed

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by tjchadaga** [comment]
@Junchao-Mellanox - can this be closed?

**Comment by Junchao-Mellanox** [comment]
Yes, the fix has been merged.
