### ISSUE TITLE
[techsupport] show cli invocation is dependent on availability of redis connectivity

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#14880]
#### Description

show cli invocation is dependent on availability of redis connection

#### Steps to reproduce the issue:

Very rare to repro, but is seen during system init and auto-techsupport being triggered around the same time.

```
Apr 27 04:08:53.222405 sonic  INFO systemd[1]: Reloading.
Apr 27 04:08:53.510773 sonic  ERR coredump_gen_handler.py[71993]: show techsupport failed with exit code 1, stderr: Traceback (most recent call last):#012  File "/usr/local/bin/show", line 5, in <module>#012    from show.main import cli#012  File "/usr/local/lib/python3.9/dist-packages/show/main.py", line 297, in <module>#012    if is_gearbox_configured():#012  File "/usr/local/lib/python3.9/dist-packages/show/main.py", line 240, in is_gearbox_configured#012    app_db.connect(app_db.APPL_DB)#012  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1781, in connect#012    return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)#012RuntimeError: Unable to connect to redis: Cannot assign requested address
```

Even If the connection fails for some other reason i.e. database down etc, techsupport invocation should not be failed regardless.

#### Describe the results you received:

Clearly, generate_dump invocation failed because of the failure in show cli i.e "Unable to connect to redis: Cannot assign requested address"

#### Describe the results you expected:

IMO, user should be able to collect techsupport dump regardless of the system state. 

[sysdump_test_reboot.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/11357755/sysdump_test_reboot.tar.gz)

**Comment by gechiang** [comment]
This seems to be due to "chassis" changes that made a change in loopback address?
this needs to be discussed with the "chassis" community to change from unix socket?
Change wrapper so that it does not break pizzabox platforms?
@yxieca can you help find the PR that made the change that is causing this issue?
