### ISSUE TITLE
RuntimeError in lag_keepalive.py during warm-reboot

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#15211]
#### Steps to reproduce the issue:
1. Execute warm-reboot repeatedly. Happens not every time.

#### Describe the results you received:

```
Thu 25 May 2023 01:48:05 PM IDT Starting lag_keepalive to send LACPDUs ...
/usr/local/lib/python3.9/dist-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/usr/local/lib/python3.9/dist-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
Traceback (most recent call last):
  File "/usr/local/bin/lag_keepalive.py", line 102, in <module>
    main()
  File "/usr/local/bin/lag_keepalive.py", line 99, in main
    lag_keepalive(lag_member_to_packet)
  File "/usr/local/bin/lag_keepalive.py", line 65, in lag_keepalive
    for lag_member, packet in lag_member_to_packet.items():
RuntimeError: dictionary changed size during iteration
```

#### Describe the results you expected:

No crash.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202211_RC16.2-335271f650_Internal
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 335271f650
Build date: Tue May 23 10:44:15 UTC 2023
Built by: sw-r2d2-bot@r-build-sonic-ci03-244

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1828K21616
Model Number: MSN2700-CS2F
Hardware Revision: A1
Uptime: 13:53:59 up 4 min,  1 user,  load average: 2.68, 2.35, 1.08
Date: Thu 25 May 2023 13:53:59

Docker images:
REPOSITORY                                         TAG                                 IMAGE ID       SIZE
docker-syncd-mlnx                                  202211_RC16.2-335271f650_Internal   b4652e107e6d   877MB
docker-syncd-mlnx                                  latest                              b4652e107e6d   877MB
docker-orchagent                                   202211_RC16.2-335271f650_Internal   0fcc8dd5a864   475MB
docker-orchagent                                   latest                              0fcc8dd5a864   475MB
docker-platform-monitor                            202211_RC16.2-335271f650_Internal   1969580ad37a   877MB
docker-platform-monitor                            latest                              1969580ad37a   877MB
docker-snmp                                        202211_RC16.2-335271f650_Internal   b0d4494a6fab   485MB
docker-snmp                                        latest                              b0d4494a6fab   485MB
docker-teamd                                       202211_RC16.2-335271f650_Internal   78f868424aef   456MB
docker-teamd                                       latest                              78f868424aef   456MB
docker-fpm-frr                                     202211_RC16.2-335271f650_Internal   d7a4508220ee   486MB
docker-fpm-frr                                     latest                              d7a4508220ee   486MB
docker-sonic-telemetry                             202211_RC16.2-335271f650_Internal   9c6b77cba6d3   738MB
docker-sonic-telemetry                             latest                              9c6b77cba6d3   738MB
docker-dhcp-relay                                  latest                              8bab9d4619e0   450MB
docker-macsec                                      latest                              f296f603ac13   459MB
docker-eventd                                      202211_RC16.2-335271f650_Internal   04b7342c8189   440MB
docker-eventd                                      latest                              04b7342c8189   440MB
docker-router-advertiser                           202211_RC16.2-335271f650_Internal   aabd703fbbc8   440MB
docker-router-advertiser                           latest                              aabd703fbbc8   440MB
docker-database                                    202211_RC16.2-335271f650_Internal   9e8bf2ff882d   439MB
docker-database                                    latest                              9e8bf2ff882d   439MB
docker-mux                                         202211_RC16.2-335271f650_Internal   f0dcef641839   487MB
docker-mux                                         latest                              f0dcef641839   487MB
docker-lldp                                        202211_RC16.2-335271f650_Internal   57d859370f14   482MB
docker-lldp                                        latest                              57d859370f14   482MB
docker-sonic-p4rt                                  202211_RC16.2-335271f650_Internal   edd30d7c8cb5   522MB
docker-sonic-p4rt                                  latest                              edd30d7c8cb5   522MB
docker-nat                                         202211_RC16.2-335271f650_Internal   a4238b99d0ae   423MB
docker-nat                                         latest                              a4238b99d0ae   423MB
docker-sflow                                       202211_RC16.2-335271f650_Internal   6e8b42e3fd52   421MB
docker-sflow                                       latest                              6e8b42e3fd52   421MB
docker-sonic-mgmt-framework                        202211_RC16.2-335271f650_Internal   58a535d9e7d2   551MB
docker-sonic-mgmt-framework                        latest                              58a535d9e7d2   551MB
urm.nvidia.com/sw-nbu-sws-sonic-docker/sonic-wjh   1.5.0-202211-internal-4             f79be67c5ca6   323MB
```
#### Output of `show techsupport`:

[sonic_dump_qa-eth-vt02-5-2700a1_20230525_135151.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/11563993/sonic_dump_qa-eth-vt02-5-2700a1_20230525_135151.tar.gz)

**Comment by stepanblyschak** [comment]
@vaibhavhd
