### ISSUE TITLE
[Build] fix docker-sonic-mgmt build

### ISSUE THREAD

**Issue by shbalaku-microsoft** [sonic-net/sonic-buildimage#15567]
#### Description

Building docker-sonic-mgmt docker image is failing. 
Trying to set up the test bed as mentioned (here)[https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testbed/README.testbed.Setup.md] and stuck at the **Build and run docker-sonic-mgmt**

#### Steps to reproduce the issue:
(Assuming we have set up the host and clone the repositories)
1. cd sonic-buildimage
2. make configure PLATFORM=generic
3. make target/docker-sonic-mgmt.gz

#### Describe the results you received:
1. PYAML Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 180, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 419, in _resolve_one
    assert req_to_install.user_supplied
```

2. Azure-Cli error:
```
The following packages have unmet dependencies:
 azure-cli : Depends: libc6 (>= 2.35) but 2.31-0ubuntu9.9 is to be installed
             Depends: libffi8 (>= 3.4) but it is not installable
             Depends: libnsl2 (>= 1.0) but it is not installable
             Depends: libssl3 (>= 3.0.0~~alpha1) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c curl -sL https://aka.ms/InstallAzureCLIDeb | bash' returned a non-zero code: 100
```

#### Describe the results you expected:

Successful build

**Comment by shbalaku-microsoft** [comment]
@lguohan for awareness.

**Comment by prgeor** [comment]
@wangxin can you take a look into the sonic-mgmt docker build issue
