### ISSUE TITLE
[chasssis]Error seen with config load_minigraph -y --override_config in consig_setup service in SUPERVISOR

### ISSUE THREAD

**Issue by judyjoseph** [sonic-net/sonic-buildimage#16164]
#### Description

See this error with config load_minigraph -y --override_config in consig_setup service in SUPERVISOR

```
Aug 14 19:27:59 sonic config-setup[9481]: Traceback (most recent call last):
Aug 14 19:27:59 sonic config-setup[9481]: Traceback (most recent call last):
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/bin/config", line 8, in <module>
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/bin/config", line 8, in <module>
Aug 14 19:27:59 sonic config-setup[9481]:     sys.exit(config())
Aug 14 19:27:59 sonic config-setup[9481]:     sys.exit(config())
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
Aug 14 19:27:59 sonic config-setup[9481]:     return self.main(*args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:     return self.main(*args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
Aug 14 19:27:59 sonic config-setup[9481]:     rv = self.invoke(ctx)
Aug 14 19:27:59 sonic config-setup[9481]:     rv = self.invoke(ctx)
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Aug 14 19:27:59 sonic config-setup[9481]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:     return ctx.invoke(self.callback, **ctx.params)
Aug 14 19:27:59 sonic config-setup[9481]:     return ctx.invoke(self.callback, **ctx.params)
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:     return callback(*args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:     return callback(*args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 64, in new_func
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 64, in new_func
Aug 14 19:27:59 sonic config-setup[9481]:     return ctx.invoke(f, obj, *args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:     return ctx.invoke(f, obj, *args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
Aug 14 19:27:59 sonic config-setup[9481]:     return callback(*args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:     return callback(*args, **kwargs)
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/config/main.py", line 1823, in override_config_table
Aug 14 19:27:59 sonic config-setup[9481]:   File "/usr/local/lib/python3.9/dist-packages/config/main.py", line 1823, in override_config_table
Aug 14 19:27:59 sonic config-setup[9481]:     ns_config_input = config_input[ns]
Aug 14 19:27:59 sonic config-setup[9481]:     ns_config_input = config_input[ns]
Aug 14 19:27:59 sonic config-setup[9481]: KeyError: 'asic14'
Aug 14 19:27:59 sonic config-setup[9481]: KeyError: 'asic14'
```

#### Steps to reproduce the issue:
1. Boot the SUPERVISOR card with the golden_config_db.json file. Sample format 
```
{
  "localhost": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic0": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic1": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic2": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic3": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic4": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic5": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic6": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic7": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic8": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic9": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic10": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic11": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic12": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  },
  "asic13": {
    "KUBERNETES_MASTER": {
      "SERVER": {
        "ip": "",
        "disable": "true"
      }
    },
    "MACSEC_PROFILE": {}
  }
}
```

3.
4.

#### Describe the results you received:
Error shown when the "asic" section mapped to a namespace which is present in the device is missing in the golden_config_db.json 

#### Describe the results you expected:
No error

#### Output of `show version`:

```
admin@str2-7250-sup-1:~$ show version 

SONiC Software Version: SONiC.20220530.38
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 4115919589
Build date: Fri Jul 28 01:24:14 UTC 2023
Built by: cloudtest@8ec96c8ac000000```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

<!--
     Also attach debug file produced by `sudo generate_dump`
-->

**Comment by wen587** [comment]
@qiluo-msft  for vis of this special case.
