### ISSUE TITLE
test_upgrade_path fails for 202012->202305 due to APPLY_VIEW event counters not matching

### ISSUE THREAD

**Issue by andywongarista** [sonic-net/sonic-buildimage#16194]
#### Description

test_upgrade_path from 202012 to 202305 currently fails due to `FAIL: Event APPLY_VIEW counters did not match. Started 1 times, and ended 0 times`

#### Steps to reproduce the issue:
1. Run test upgrade_path/test_upgrade_path.py::test_upgrade_path using reboot type "warm", 202012 as the base image, and 202305 as the target image
2. Check results
3.

#### Describe the results you received:
```
self = <tests.common.fixtures.advanced_reboot.AdvancedReboot object at 0x7fbd89db8f40>

    def runRebootTest(self):
        # Run advanced-reboot.ReloadTest for item in preboot/inboot list
        count = 0
        result = True
        test_results = dict()
        for rebootOper in self.rebootData['sadList']:
            count += 1
            test_case_name = str(self.request.node.name) + str(rebootOper)
            test_results[test_case_name] = list()
            try:
                if self.preboot_setup:
                    self.preboot_setup()
                if self.advanceboot_loganalyzer:
                    pre_reboot_analysis, post_reboot_analysis = self.advanceboot_loganalyzer
                    marker = pre_reboot_analysis()
                event_counters = self.__setupRebootOper(rebootOper)
                thread = InterruptableThread(
                    target=self.__runPtfRunner,
                    kwargs={"rebootOper": rebootOper})
                thread.daemon = True
                thread.start()
                # give the test REBOOT_CASE_TIMEOUT (1800s) to complete the reboot with IO,
                # and then additional 300s to examine the pcap, logs and generate reports
                ptf_timeout = REBOOT_CASE_TIMEOUT + 300
                thread.join(timeout=ptf_timeout, suppress_exception=True)
                self.ptfhost.shell("pkill -f 'ptftests advanced-reboot.ReloadTest'", module_ignore_errors=True)
                # the thread might still be running, and to catch any exceptions after pkill allow 10s to join
                thread.join(timeout=10)
                self.__verifyRebootOper(rebootOper)
                if self.duthost.num_asics() == 1 and not check_bgp_router_id(self.duthost, self.mgFacts):
                    test_results[test_case_name].append("Failed to verify BGP router identifier is Loopback0 on %s" %
                                                        self.duthost.hostname)
                if self.postboot_setup:
                    self.postboot_setup()
            except Exception:
                traceback_msg = traceback.format_exc()
                logger.error("Exception caught while running advanced-reboot test on ptf: \n{}".format(traceback_msg))
                test_results[test_case_name].append("Exception caught while running advanced-reboot test on ptf")
            finally:
                # capture the test logs, and print all of them in case of failure, or a summary in case of success
                log_dir = self.__fetchTestLogs(rebootOper)
                self.print_test_logs_summary(log_dir)
                if self.advanceboot_loganalyzer:
                    verification_errors = post_reboot_analysis(marker, event_counters=event_counters,
                                                               reboot_oper=rebootOper, log_dir=log_dir)
                    if verification_errors:
                        logger.error("Post reboot verification failed. List of failures: {}"
                                     .format('\n'.join(verification_errors)))
                        test_results[test_case_name].extend(verification_errors)
                self.acl_manager_checker(test_results[test_case_name])
                self.__clearArpAndFdbTables()
                self.__revertRebootOper(rebootOper)
            if 1 < len(self.rebootData['sadList']) != count:
                time.sleep(TIME_BETWEEN_SUCCESSIVE_TEST_OPER)
            failed_list = [(testcase, failures) for testcase, failures in list(test_results.items())
                           if len(failures) != 0]
>       pytest_assert(len(failed_list) == 0, "Advanced-reboot failure. Failed test: {}, "
                                             "failure summary:\n{}".format(self.request.node.name, failed_list))
E       Failed: Advanced-reboot failure. Failed test: test_upgrade_path[gd385], failure summary:
E       [('test_upgrade_path[gd385]None', ['Exception caught while running advanced-reboot test on ptf', 'FAIL: Event
APPLY_VIEW counters did not match. Started 1 times, and ended 0 times'])]

count      = 1
event_counters = {'APPLY_VIEW': 1, 'LAG_READY': 4, 'PORT_READY': 16, 'SAI_CREATE_SWITCH': 1}
failed_list = [('test_upgrade_path[gd385]None', ['Exception caught while running advanced-reboot test on ptf', 'FAIL:
Event APPLY_VIEW counters did not match. Started 1 times, and ended 0 times'])]
log_dir    = '/data/tests/logs/platform_tests/test_upgrade_path[gd385]/'
marker     = 'test_advanced_reboot_test_upgrade_path[gd385].2023-08-17-20:35:35'
post_reboot_analysis = <function advanceboot_loganalyzer.<locals>.post_reboot_analysis at 0x7fbd8a581af0>
pre_reboot_analysis = <function advanceboot_loganalyzer.<locals>.pre_reboot_analysis at 0x7fbd8a581c10>
ptf_timeout = 2400
rebootOper = None
result     = True
self       = <tests.common.fixtures.advanced_reboot.AdvancedReboot object at 0x7fbd89db8f40>
test_case_name = 'test_upgrade_path[gd385]None'
test_results = {'test_upgrade_path[gd385]None': ['Exception caught while running advanced-reboot test on ptf', 'FAIL:
Event APPLY_VIEW counters did not match. Started 1 times, and ended 0 times']}
thread     = <InterruptableThread(Thread-190, stopped daemon 140450723784448)>
traceback_msg = 'Traceback (most recent call last):\n  File "/data/tests/common/fixtures/advanced_reboot.py", line 572
, in runRebootTe...-----------------------------", "2023-08-17 20:56:15 : Additional info:", "2023-08-17 20:56:15 : --
--------------"]}\n'
verification_errors = ['FAIL: Event APPLY_VIEW counters did not match. Started 1 times, and ended 0 times']

common/fixtures/advanced_reboot.py:601: Failed

```

#### Describe the results you expected:
Expect test to pass

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vmittal-msft** [comment]
@vaibhavhd Could this be side effect of other warm boot issue we are working on ?

**Comment by vmittal-msft** [comment]
@andywongarista please upload output of "show techsupport" to this issue.

**Comment by vaibhavhd** [comment]
> @vaibhavhd Could this be side effect of other warm boot issue we are working on ?
> 
> testcase = 'test_upgrade_path[gd385]None' thread = <InterruptableThread(Thread-101, stopped daemon 140024548927232)> traceback_msg = 'Traceback (most recent call last):\n File "/data/tests/common/fixtures/advanced_reboot.py", line 543, in runRebootTe. ..23:50:59 : FAILED:10.250.25.4:BGP route GR timeout: neighbor 10.0.0.60 (ASN 65100)", "2023-08-22 23:50:59 : FAILE"]}\n' verification_errors = ['FAIL: Event SAI_CREATE_SWITCH was found 2 times, when expected exactly 1 times', 'FAIL: Event APPLY_VIEW was fo und 2...t match. Started 2 times, and ended 1 times', 'FAIL: Event LAG_READY was found 8 times, when expected exactly 4 times']
> 
> common/fixtures/advanced_reboot.py:601: Failed

It could be. This can be ascertained by looking at the syslog from failure run. The error here is saying that all LAGs flapped. That would be the case when OA crashes. We need syslog and sairedis log to confirm the root cause here.
Also, what platform was the test executed on? There is a known issue w/ TD3 SAI.

**Comment by saiarcot895** [comment]
```
Aug 21 23:35:10.107734 gd385 WARNING swss#orchagent: :- querySwitchCapability: Could not query switch level DSCP to TC map -2
Aug 21 23:35:10.107734 gd385 ERR swss#orchagent: :- applyDscpToTcMapToSwitch: Switch level DSCP to TC QoS map configuration is not supported
```

This one is also a known issue.

**Comment by andywongarista** [comment]
```
gd385 ERR swss#orchagent: :- syncd_apply_view: Failed to notify syncd APPLY_VIEW -1
gd385 ERR swss#orchagent: :- on_switch_shutdown_request: Syncd stopped
```
Seems like something is causing syncd to shutdown and OA to subsequently crash, though it's not clear from the logs what the problem in syncd is. My guess is that `Syncd::sendShutdownRequest` was called, however I don't see any of the method's corresponding log statements in the logs.

**Comment by andywongarista** [comment]
Seeing below failure on SAI 8.4.21
```
E       Failed: Advanced-reboot failure. Failed test: test_upgrade_path[gd231], failure summary:
E       [('test_upgrade_path[gd231]None', ['FAIL: Event SAI_CREATE_SWITCH counters did not match. Started 1 times, and ended 0 times', 'FAIL: Event APPLY_VIEW was found
0 times, when expected exactly 1 times'])]
```
