### ISSUE TITLE
[Chassis][202205] Slow memory leak seen in syncd docker/process 

### ISSUE THREAD

**Issue by judyjoseph** [sonic-net/sonic-buildimage#16564]
#### Description

It was found that the syncd docker takes up huge memory after being run for a few days 

```
CONTAINER ID   NAME        CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
7141004b3cd7   snmp        2.63%     73.35MiB / 31.23GiB   0.23%     0B / 0B           13.6MB / 131kB    8
983f872de18b   telemetry   0.66%     193.7MiB / 31.23GiB   0.61%     0B / 0B           35.3MB / 90.1kB   51
1ebaf6fba5cd   lldp1       0.03%     70.7MiB / 31.23GiB    0.22%     2.46GB / 7.09GB   319kB / 115kB     11
6937739eb2e2   lldp0       0.03%     72.74MiB / 31.23GiB   0.23%     6.13GB / 11.3GB   967kB / 115kB     11
07cfaa73a95e   lldp        0.03%     70.53MiB / 31.23GiB   0.22%     0B / 0B           5.59MB / 115kB    11
39ae6a45a100   pmon        0.45%     214.4MiB / 31.23GiB   0.67%     0B / 0B           12.1MB / 172kB    16
65e892921486   macsec0     0.75%     59.5MiB / 31.23GiB    0.19%     6.13GB / 11.3GB   2.88MB / 61.4kB   24
4ef70c4c2492   macsec1     0.03%     35.7MiB / 31.23GiB    0.11%     2.46GB / 7.09GB   373kB / 65.5kB    8
ebdc27e3788d   radv        0.01%     33.34MiB / 31.23GiB   0.10%     0B / 0B           401kB / 81.9kB    6
12bcd38be9af   bgp1        0.20%     211.8MiB / 31.23GiB   0.66%     2.46GB / 7.09GB   6.16MB / 5.76GB   24
43ddbfacf608   bgp0        0.21%     232.3MiB / 31.23GiB   0.73%     6.13GB / 11.3GB   8.79MB / 5.76GB   24
92d7efdb2546   syncd0      68.75%    18.1GiB / 31.23GiB    57.95%    6.13GB / 11.3GB   184MB / 115kB     50  <<<<<<<<<<<<<<<
4c3668610680   syncd1      59.93%    1.123GiB / 31.23GiB   3.60%     2.46GB / 7.09GB   88.1MB / 111kB    49
8dc163e64f6b   teamd1      0.04%     35.59MiB / 31.23GiB   0.11%     2.46GB / 7.09GB   36.9kB / 94.2kB   12
465a42dcca3f   teamd0      0.60%     46.78MiB / 31.23GiB   0.15%     6.13GB / 11.3GB   4.41MB / 94.2kB   16
4083ec5651d3   swss0       0.13%     61.32MiB / 31.23GiB   0.19%     6.13GB / 11.3GB   2.22MB / 340kB    37
2b8a4fdada2a   swss1       0.13%     66.08MiB / 31.23GiB   0.21%     2.46GB / 7.09GB   17.5MB / 250kB    37
bf5bd0e87111   restapi     0.02%     84.55MiB / 31.23GiB   0.26%     0B / 0B           434kB / 86kB      8
0ca7aac8d7d4   acms        0.02%     53.31MiB / 31.23GiB   0.17%     0B / 0B           152kB / 241MB     9
69e53f9d4d05   database0   8.05%     162.3MiB / 31.23GiB   0.51%     6.13GB / 11.3GB   600kB / 77.8kB    11
e507b53f2d5b   database1   0.41%     95.58MiB / 31.23GiB   0.30%     2.46GB / 7.09GB   307kB / 77.8kB    11
dd33dd0b59a1   database    0.20%     91.4MiB / 31.23GiB    0.29%     0B / 0B           45.3MB / 73.7kB   11

```

#### Steps to reproduce the issue:
1. Enable flex counter 
2. Leave the switch with traffic on for a few days
3.

#### Describe the results you expected:
```
CONTAINER ID   NAME        CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
74a8bc109e6f   telemetry   0.70%     177.9MiB / 31.25GiB   0.56%     0B / 0B         111kB / 90.1kB   50
37aab75944fd   snmp        5.93%     102MiB / 31.25GiB     0.32%     0B / 0B         0B / 131kB       8
d900f12fddd7   macsec0     0.03%     35.03MiB / 31.25GiB   0.11%     527MB / 906MB   0B / 65.5kB      8
c8f2c76213c1   macsec1     0.03%     33.08MiB / 31.25GiB   0.10%     537MB / 905MB   0B / 65.5kB      8
cfdb90074dba   lldp0       0.02%     70.29MiB / 31.25GiB   0.22%     527MB / 906MB   0B / 115kB       11
7e16dbdbcca5   radv        0.02%     32.77MiB / 31.25GiB   0.10%     0B / 0B         0B / 81.9kB      6
c44a2bdc166f   lldp1       0.02%     69.07MiB / 31.25GiB   0.22%     537MB / 905MB   0B / 115kB       11
e89f31947d62   syncd1      58.26%    1.429GiB / 31.25GiB   4.57%     537MB / 905MB   0B / 106kB       49   <<<<<<<<<<<<
1ca3981e78a0   syncd0      72.91%    1.433GiB / 31.25GiB   4.59%     527MB / 906MB   135kB / 106kB    51   <<<<<<<<<<<
a4f56b99932d   teamd0      0.13%     36.99MiB / 31.25GiB   0.12%     527MB / 906MB   0B / 94.2kB      13
0c7be52e5051   bgp0        0.07%     374.4MiB / 31.25GiB   1.17%     527MB / 906MB   0B / 400MB       24
5e2c659af851   teamd1      0.13%     36.96MiB / 31.25GiB   0.12%     537MB / 905MB   0B / 98.3kB      13
a0b697a9d6ae   bgp1        0.05%     357.9MiB / 31.25GiB   1.12%     537MB / 905MB   0B / 112MB       24
aa512cfc57ac   swss1       0.13%     270.3MiB / 31.25GiB   0.84%     537MB / 905MB   0B / 250kB       37
4a041370adc9   swss0       0.13%     261.4MiB / 31.25GiB   0.82%     527MB / 906MB   0B / 250kB       37
d77065cb01d7   lldp        0.03%     69.82MiB / 31.25GiB   0.22%     0B / 0B         0B / 115kB       11
f19aeea2cd3d   pmon        0.43%     198.7MiB / 31.25GiB   0.62%     0B / 0B         0B / 127kB       16
5843bb18e496   restapi     0.03%     38.61MiB / 31.25GiB   0.12%     0B / 0B         0B / 131kB       8
a2341ca5e60b   acms        0.02%     52.2MiB / 31.25GiB    0.16%     0B / 0B         0B / 496kB       9
36aa7540762b   database0   4.04%     187.2MiB / 31.25GiB   0.58%     527MB / 906MB   0B / 127kB       11
506ee9f2c5fc   database1   3.04%     193MiB / 31.25GiB     0.60%     537MB / 905MB   0B / 127kB       11
d56d6ce6fdfc   database    0.32%     56.86MiB / 31.25GiB   0.18%     0B / 0B         0B / 73.7kB      11
```

#### Output of `show version`:

```
jujoseph@STG01-0101-0200-01T2-lc01:~$ show version 

SONiC Software Version: SONiC.20220530.38
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 4115919589
Build date: Fri Jul 28 01:24:14 UTC 2023
Built by: cloudtest@8ec96c8ac000000```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

<!--
     Also attach debug file produced by `sudo generate_dump`
-->

**Comment by judyjoseph** [comment]
To add more details

**Comment by judyjoseph** [comment]
Couple of findings 

1. When we enable pfcwd, the memory leak is seen. If pfcwd is disabled -- no memory increase.
2. Adding gdb script, used the dbg docker image and attach gdb to syncd proecess. Below is the sample gdb script used, Thanks to Kamil for helping out with the gdb script

```
# enable attaching in kernel
# sudo sysctl -w kernel.yama.ptrace_scope=0
# attach: gdb --pid=$(pgrep syncd) --command=script

set pagination off
  set breakpoint pending on
  set logging file gdbcmd1.out
  set logging on
  break malloc
  commands
  set $mallocsize = (unsigned long long) $rdi
  continue
  end
  break *(malloc+173)
  commands
  printf "ALLOC(%llx) = 0x%016llx\n", $mallocsize, $rax
  bt
  continue
  end

  break calloc
  commands
  set $mallocsize = (unsigned long long) $rdi
  continue
  end
  break *(calloc+213)
  commands
  printf "ALLOC(%llx) = 0x%016llx\n", $mallocsize, $rax
  bt
  continue
  end

  break realloc
  commands
  set $mallocsize = (unsigned long long) $rdi
  continue
  end
  break *(realloc+275)
  commands
  printf "ALLOC(%llx) = 0x%016llx\n", $mallocsize, $rax
  bt
  continue
  end

  break free
  commands
  printf "FREE(0x%016llx)\n", (unsigned long long) $rdi
  continue
  end
  continue
```

Below is an additional traceback coming with gdb when the pfwd was **enabled** 

```
Thread 40 "syncd" hit Breakpoint 1, 0x00007fcfcc85fd30 in malloc () from /lib/x86_64-linux-gnu/libc.so.6
ptr 0x0 free
#0  0x00007fcfcc85fd30 in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fcfd4894b09 in sal_alloc2 () from /usr/lib/libsai.so.1
#2  0x00007fcfd6f373fb in calc_ecc () from /usr/lib/libsai.so.1
#3  0x00007fcfd4cd7878 in ?? () from /usr/lib/libsai.so.1
#4  0x00007fcfd4cd8257 in ?? () from /usr/lib/libsai.so.1
#5  0x00007fcfd4cd85fd in dbal_hl_hook_entry_get () from /usr/lib/libsai.so.1
#6  0x00007fcfd4cd3bf0 in dbal_hl_entry_get () from /usr/lib/libsai.so.1
#7  0x00007fcfd4ca0e25 in dbal_actions_access_entry_get () from /usr/lib/libsai.so.1
#8  0x00007fcfd4cacfc0 in dbal_entry_get () from /usr/lib/libsai.so.1
#9  0x00007fcfd3166b5d in dnx_	_dbal_queue_resources_statistics_current_get () from /usr/lib/libsai.so.1
#10 0x00007fcfd22dbeae in ?? () from /usr/lib/libsai.so.1         ------------------ _brcm_sai_dnx_cosq_ecgm_stats_get
#11 0x00007fcfd22ddd5c in ?? () from /usr/lib/libsai.so.1         ------------------ _brcm_sai_dnx_fap_cosq_stat_get
#12 0x00007fcfd22de39a in ?? () from /usr/lib/libsai.so.1         ------------------ _brcm_sai_dnx_cosq_stat_get/_brcm_sai_dnx_get_port_egress_drop_pkt_cnt
#13 0x0000561d8146ac2f in syncd::VendorSai::getStats (this=0x561d8279f080, object_type=SAI_OBJECT_TYPE_QUEUE, object_id=845614636072964, number_of_counters=2, counter_ids=0x561d9d241d40, counters=0x7fcf14049fd0) at VendorSai.cpp:435
#14 0x0000561d814d6b31 in syncd::FlexCounter::collectQueueCounters (this=0x561d9d3666b0, countersTable=...) at FlexCounter.cpp:1575
#15 0x0000561d814c9054 in syncd::FlexCounter::collectCounters (this=0x561d9d3666b0, countersTable=...) at FlexCounter.cpp:1454
#16 0x0000561d814e15bc in syncd::FlexCounter::flexCounterThreadRunFunction (this=0x561d9d3666b0) at FlexCounter.cpp:2395
#17 0x00007fcfcca96ed0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007fcfccc5bea7 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007fcfcc8d5a2f in clone () from /lib/x86_64-linux-gnu/libc.so.6
ptr 0x0 alloc

```

**Comment by judyjoseph** [comment]
Next steps:
> try to use valgrind if possible to find the memory leak ?
> try using an old SAI debian to see if this was introduced recently ?

**Comment by judyjoseph** [comment]
@saksarav-nokia @rawal01

**Comment by judyjoseph** [comment]
Fixed via Brcm CSP : CS00012315073
