### ISSUE TITLE
[Mellanox] name 'SX_PORT_MODULE_STATUS_INITIALIZING' is not defined

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-buildimage#16648]
#### Description
We saw below error on 20223 image, Mellanox device.
```
admin@str2-msn2700-spy-1:~$ sudo sfputil show error-status -hw
```
Back trace
```
Traceback (most recent call last):
  File "/usr/local/bin/sfputil", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 955, in error_status
    output_table = fetch_error_status_from_platform_api(port)
  File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 896, in fetch_error_status_from_platform_api
    error_description = platform_chassis.get_sfp(physical_port).get_error_description()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/sfp.py", line 440, in get_error_description
    if oper_status == SX_PORT_MODULE_STATUS_INITIALIZING:
NameError: name 'SX_PORT_MODULE_STATUS_INITIALIZING' is not defined
```
It should be a syntax issue in sfp.py.

#### Steps to reproduce the issue:
1. Run CLI `sudo sfputil show error-status --fetch-from-hardware`
2.
3.

#### Describe the results you received:
An exception is thrown when running command `sudo sfputil show error-status --fetch-from-hardware`

#### Describe the results you expected:
The command should complete without error.

#### Output of `show version`:
The image we are running is an internal build on Sep 14.

```
SONiC Software Version: SONiC.20230531.03
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: cedd805bac
Build date: Thu Sep 14 14:24:07 UTC 2023
Built by: cloudtest@adaa75e0c000003
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by bingwang-ms** [comment]
@volodymyrsamotiy Can you please assign someone to take a look? Thanks

**Comment by judyjoseph** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/16545 Fixes it, @bingwang-ms could you check
