### ISSUE TITLE
fanshow and fan management are broken on Dell N3248TE-ON and current release

### ISSUE THREAD

**Issue by justindthomas** [sonic-net/sonic-buildimage#16666]
#### Description

I'm new to SONiC and installed it on a Dell N3248TE-ON I received a couple of days ago. On initial boot, the switch actively managed the fans (i.e., speed was constantly changing, presumably in response to load, but were at an average pretty quiet speed).

After installing SONiC, the fans just run at a high (loud) speed constantly. Commands to show the fan status fail with Python errors.

```python
root@sonic:~# show platform fan
Traceback (most recent call last):
  File "/usr/local/bin/fanshow", line 85, in <module>
    fanShow.show()
  File "/usr/local/bin/fanshow", line 75, in show
    table.append((data_dict[DRAWER_FIELD_NAME], data_dict[LED_STATUS_FIELD_NAME], name, speed, data_dict[DIRECTION_FIELD_NAME], presence, status,
KeyError: 'drawer_name'
```

```python
root@sonic:~# show environment
  File "/usr/bin/platform_sensors.py", line 20
    print line
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(line)?
```

#### Steps to reproduce the issue:
1. Turn it on.
2. `show platform fan`
3. `show environment`

#### Describe the results you received:
1. Loud, constantly high fan speed.
2. Error message (above) for `show platform fan`
3. Error message (above) for `show environment`

#### Describe the results you expected:
1. Managed fan speed like the OEM (Dell) software on the switch.
2. Something showing me details about the fans.
3. Something showing me details about the environment.

#### Output of `show version`:

```
root@sonic:~# show ver

SONiC Software Version: SONiC.master.366447-72341a7ee
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 72341a7ee
Build date: Tue Sep 19 12:43:09 UTC 2023
Built by: AzDevOps@vmss-soni0021EJ

Platform: x86_64-dellemc_n3248te_c3338-r0
HwSKU: DellEMC-N3248TE
ASIC: broadcom
ASIC Count: 1
Serial Number: 4GNXV43
Model Number: 0WNWT9
Hardware Revision: 
Uptime: 00:12:28 up 1 day, 16:09,  1 user,  load average: 0.54, 0.54, 0.60
Date: Sat 23 Sep 2023 00:12:28

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-gbsyncd-broncos        latest                    864fedd2e6a4   349MB
docker-gbsyncd-broncos        master.366447-72341a7ee   864fedd2e6a4   349MB
docker-gbsyncd-credo          latest                    e9b286143afd   319MB
docker-gbsyncd-credo          master.366447-72341a7ee   e9b286143afd   319MB
docker-syncd-brcm             latest                    c77995c75fb4   673MB
docker-syncd-brcm             master.366447-72341a7ee   c77995c75fb4   673MB
docker-macsec                 latest                    123ab862c7ba   325MB
docker-dhcp-relay             latest                    874362975b61   307MB
docker-orchagent              latest                    3a670bf2f74c   335MB
docker-orchagent              master.366447-72341a7ee   3a670bf2f74c   335MB
docker-fpm-frr                latest                    3102e2ac34f7   355MB
docker-fpm-frr                master.366447-72341a7ee   3102e2ac34f7   355MB
docker-eventd                 latest                    445ee5b2391d   299MB
docker-eventd                 master.366447-72341a7ee   445ee5b2391d   299MB
docker-nat                    latest                    fe6b6887a1a9   326MB
docker-nat                    master.366447-72341a7ee   fe6b6887a1a9   326MB
docker-sflow                  latest                    0bee6fa20dea   325MB
docker-sflow                  master.366447-72341a7ee   0bee6fa20dea   325MB
docker-teamd                  latest                    b291ac9beef4   323MB
docker-teamd                  master.366447-72341a7ee   b291ac9beef4   323MB
docker-snmp                   latest                    529de93e25be   338MB
docker-snmp                   master.366447-72341a7ee   529de93e25be   338MB
docker-sonic-telemetry        latest                    ab34c1cab1d0   600MB
docker-sonic-telemetry        master.366447-72341a7ee   ab34c1cab1d0   600MB
docker-platform-monitor       latest                    b908f4ae5295   419MB
docker-platform-monitor       master.366447-72341a7ee   b908f4ae5295   419MB
docker-router-advertiser      latest                    7a55092937dd   299MB
docker-router-advertiser      master.366447-72341a7ee   7a55092937dd   299MB
docker-lldp                   latest                    5a25c9484782   341MB
docker-lldp                   master.366447-72341a7ee   5a25c9484782   341MB
docker-database               latest                    d6b0da49e72c   299MB
docker-database               master.366447-72341a7ee   d6b0da49e72c   299MB
docker-mux                    latest                    7dae38e79e3c   348MB
docker-mux                    master.366447-72341a7ee   7dae38e79e3c   348MB
docker-sonic-mgmt-framework   latest                    3a33b23aba95   416MB
docker-sonic-mgmt-framework   master.366447-72341a7ee   3a33b23aba95   416MB

```
#### Output of `show techsupport`:

[techsupport.txt](https://github.com/sonic-net/sonic-buildimage/files/12702529/techsupport.txt)

#### Additional information you deem important (e.g. issue happens only occasionally):

The dump file is 31MB and GitHub rejects files over 25MB.

**Comment by judyjoseph** [comment]
@jeff-yin Could you check with this plartform  in master ?

**Comment by justindthomas** [comment]
As I'm becoming more comfortable with SONiC, I wonder if the fact that I don't have a second PSU installed might be playing into this. I've noticed that sometimes small configuration changes can cause problems in modules that have different expectations.

I don't have a second PSU to plug in, but that might be something to investigate.

**Comment by jeff-yin** [comment]
> As I'm becoming more comfortable with SONiC, I wonder if the fact that I don't have a second PSU installed might be playing into this. I've noticed that sometimes small configuration changes can cause problems in modules that have different expectations.
> 
> I don't have a second PSU to plug in, but that might be something to investigate.

Usually the fans will go to 100% when a FAN module is removed. I don't think lacking a PSU would trigger this.
There may be some missing thermal policy code for this platform. I've asked a couple of people at Dell to look into it.
@arunlk-dell  @vpsubramaniam

**Comment by justindthomas** [comment]
I checked last night to see that all 3 fan modules were running and they're all moving air.

**Comment by justindthomas** [comment]
The speed of the fans does not seem to be dependent on the PSU presence, but the display of the status does. I picked up a second PSU and the command `show platform fan` now works.

```
jdt@sonic:~$ sudo show platform fan
  Drawer    LED            FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  -------------  -------  -----------  ----------  --------  -----------------
FanTray1    N/A  FanTray1-Fan1      57%       intake     Present        OK  20231014 02:51:38
FanTray2    N/A  FanTray2-Fan1      59%       intake     Present        OK  20231014 02:51:38
FanTray3    N/A  FanTray3-Fan1      58%       intake     Present        OK  20231014 02:51:38
     N/A    N/A       PSU1 Fan      15%       intake     Present        OK  20231014 02:51:38
     N/A    N/A       PSU2 Fan      15%       intake     Present        OK  20231014 02:51:39
```

So they aren't running at 100%, but they are running at a constant higher speed than the default software (Dell OS6, I believe) that came on the switch. Maybe that's normal? It seems like the temperatures could tolerate a less aggressive setting.

```
jdt@sonic:~$ sudo show platform temperature
                      Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
----------------------------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
 Front Panel PHY Temperature         30.687         75         0             N/A            N/A      False  20231014 02:51:39
 Middle Fan Tray Temperature         23.312         75         0             N/A            N/A      False  20231014 02:51:39
Near Front Panel Temperature         29.25          75         0             N/A            N/A      False  20231014 02:51:39
     Switch Near Temperature         29.75          75         0             N/A            N/A      False  20231014 02:51:39
     Switch Rear Temperature         24.5           75         0             N/A            N/A      False  20231014 02:51:39
```

Also, `show environment` is still broken as described in the original issue.

**Comment by arunlk-dell** [comment]
@justindthomas .. will be raising the pull request to fix the commands 'show environment' and 'show platform fan' by next week.
For the fan speed will bring in the thermal manager changes sooner.

**Comment by justindthomas** [comment]
That's great, @arunlk-dell - thanks!

**Comment by justindthomas** [comment]
For the fan speed issues, I was able to tame them by adjusting these values:

```
/sys/bus/i2c/devices/7-002c/pwm1
/sys/bus/i2c/devices/7-002c/pwm2
/sys/bus/i2c/devices/7-002c/pwm3
```

By default, these are all set to `255`, with `/sys/bus/i2c/devices/7-002c/pwm#_enable` set to `0`, which results in the continuous ~58% speed for all of them. I changed those to `100` and the speeds dropped to between 20%-30% and seems more varied, like the system is properly responding to the changing temperature.

Does that parameter adjust the aggressiveness of the thermal algorithm? I experimented with changing the `pwm_enable` to `1`, `2`, and `3`, but only `0` and `3` seem to be enabled. And `3` sets the fans to 4% and triggers a fault indicator, so that's clearly not appropriate.

**Comment by justindthomas** [comment]
PR submitted here: https://github.com/sonic-net/sonic-buildimage/pull/17508

**Comment by heiko73** [comment]
This does not work on my Dell N3248TE ... No fans shown etc.  .. However, I managed to patch fanshow to work now (threw python errors), but I am unsure where to post the changes?


```python
#!/usr/bin/python3

"""
    Script to show fan status.
"""

import os
import sys
from tabulate import tabulate
from natsort import natsorted

# mock the redis for unit test purposes #
try:
    if os.environ["UTILITIES_UNIT_TESTING"] == "1":
        modules_path = os.path.join(os.path.dirname(__file__), "..")
        test_path = os.path.join(modules_path, "tests")
        sys.path.insert(0, modules_path)
        sys.path.insert(0, test_path)
        import mock_tables.dbconnector
except KeyError:
    pass

from swsscommon.swsscommon import SonicV2Connector

header = ['Drawer', 'LED', 'FAN', 'Speed', 'Direction', 'Presence', 'Status', 'Timestamp']

FAN_TABLE_NAME = 'FAN_INFO'
DRAWER_FIELD_NAME = 'drawer_name'
SPEED_FIELD_NAME = 'speed'
DIRECTION_FIELD_NAME = 'direction'
PRESENCE_FIELD_NAME = 'presence'
STATUS_FIELD_NAME = 'status'
LED_STATUS_FIELD_NAME = 'led_status'
TIMESTAMP_FIELD_NAME = 'timestamp'


class FanShow(object):
    def __init__(self):
        self.db = SonicV2Connector(host="127.0.0.1")
        self.db.connect(self.db.STATE_DB)

    def show(self):
        keys = self.db.keys(self.db.STATE_DB, FAN_TABLE_NAME + '*')
        if not keys:
            print('Fan Not detected\n')
            return

        table = []
        for key in natsorted(keys):
            key_list = key.split('|')
            if len(key_list) != 2: # error data in DB, log it and ignore
                print('Warn: Invalid key in table FAN_INFO: {}'.format(key))
                continue

            name = key_list[1]
            data_dict = self.db.get_all(self.db.STATE_DB, key)
            try:
                speed = float(data_dict[SPEED_FIELD_NAME])
                if speed > 100:
                    speed = '{}RPM'.format(int(speed))
                else:
                    speed = '{}%'.format(data_dict[SPEED_FIELD_NAME])
            except ValueError as e:
                speed = data_dict[SPEED_FIELD_NAME]

            presence = data_dict[PRESENCE_FIELD_NAME].lower()
            presence = 'Present' if presence == 'true' else 'Not Present'
            status = data_dict[STATUS_FIELD_NAME]
            status_lower = status.lower()
            if status_lower == 'true':
                status = 'OK'
            elif status_lower == 'false':
                status = 'Not OK'
            value = data_dict.get('drawer_name', None)

            table.append((value, data_dict[LED_STATUS_FIELD_NAME], name, speed, data_dict[DIRECTION_FIELD_NAME], presence, status,
                          data_dict[TIMESTAMP_FIELD_NAME]))
        if table:
            print(tabulate(table, header, tablefmt='simple', stralign='right'))
        else:
            print('No fan status data available\n')


if __name__ == "__main__":
    fanShow = FanShow()
    fanShow.show()

```
