### ISSUE TITLE
[Bookworm] spm migrate is failing with error "No module named six"

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#16788]
#### Description

Run s2s installer into a bookworm image or run spm migrate in a bookworm image. Seems six package has to be explicitly installed in bookworm

#### Describe the results you received:

```
Command: chroot /tmp/image-master_bookworm.1-2a796ab8e_Internal-fs sonic-package-manager migrate /tmp/packages.json --dockerd-socket /tmp/docker.sock -y
Traceback (most recent call last):
  File "/usr/local/bin/sonic-package-manager", line 5, in <module>
    from sonic_package_manager.main import cli
  File "/usr/local/lib/python3.11/dist-packages/sonic_package_manager/__init__.py", line 3, in <module>
    from sonic_package_manager.manager import PackageManager
  File "/usr/local/lib/python3.11/dist-packages/sonic_package_manager/manager.py", line 28, in <module>
    from sonic_package_manager.dockerapi import DockerApi
  File "/usr/local/lib/python3.11/dist-packages/sonic_package_manager/dockerapi.py", line 12, in <module>
    from sonic_package_manager.progress import ProgressManager
  File "/usr/local/lib/python3.11/dist-packages/sonic_package_manager/progress.py", line 3, in <module>
    import enlighten
  File "/usr/local/lib/python3.11/dist-packages/enlighten/__init__.py", line 14, in <module>
    from enlighten.counter import Counter, StatusBar, SubCounter
  File "/usr/local/lib/python3.11/dist-packages/enlighten/counter.py", line 14, in <module>
    from enlighten._counter import Counter as _Counter
  File "/usr/local/lib/python3.11/dist-packages/enlighten/_counter.py", line 23, in <module>
    from enlighten._basecounter import BaseCounter, PrintableCounter
  File "/usr/local/lib/python3.11/dist-packages/enlighten/_basecounter.py", line 16, in <module>
    from enlighten._util import BASESTRING, lru_cache
  File "/usr/local/lib/python3.11/dist-packages/enlighten/_util.py", line 22, in <module>
    from blessed.colorspace import RGB_256TABLE, X11_COLORNAMES_TO_RGB
  File "/usr/local/lib/python3.11/dist-packages/blessed/__init__.py", line 14, in <module>
    from blessed.terminal import Terminal  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/blessed/terminal.py", line 21, in <module>
    from .keyboard import (_time_left,
  File "/usr/local/lib/python3.11/dist-packages/blessed/keyboard.py", line 10, in <module>
    import six
ModuleNotFoundError: No module named 'six'

```

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vivekrnv** [comment]
Fixed by https://github.com/sonic-net/sonic-utilities/pull/3019
