### ISSUE TITLE
[sonic-platform-common] Exception occurred while decoding cable vendor_pn and vendor_name

### ISSUE THREAD

**Issue by keboliu** [sonic-net/sonic-buildimage#16838]
#### Description
with recent changes in PR https://github.com/sonic-net/sonic-platform-common/pull/400 we see exception with some QSFP cables:

```
Oct 11 07:06:59.624108 sonic ERR pmon#xcvrd: Exception occured at SfpStateUpdateTask thread due to UnicodeDecodeError('utf-8', b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff', 0, 1, 'invalid start byte')
Oct 11 07:06:59.624505 sonic ERR pmon#xcvrd: Traceback (most recent call last):
Oct 11 07:06:59.624769 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2231, in run
Oct 11 07:06:59.625036 sonic ERR pmon#xcvrd:     self.task_worker(self.task_stopping_event, self.sfp_error_event)
Oct 11 07:06:59.625291 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2043, in task_worker
Oct 11 07:06:59.625556 sonic ERR pmon#xcvrd:     self.init()
Oct 11 07:06:59.625859 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1961, in init
Oct 11 07:06:59.626111 sonic ERR pmon#xcvrd:     self.retry_eeprom_set = self._post_port_sfp_info_and_dom_thr_to_db_once(port_mapping_data, self.xcvr_table_helper, self.main_thread_stop_event)
Oct 11 07:06:59.626364 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1916, in _post_port_sfp_info_and_dom_thr_to_db_once
Oct 11 07:06:59.626615 sonic ERR pmon#xcvrd:     rc = post_port_sfp_info_to_db(logical_port_name, port_mapping, xcvr_table_helper.get_intf_tbl(asic_index), transceiver_dict, stop_event)
Oct 11 07:06:59.626861 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 336, in post_port_sfp_info_to_db
Oct 11 07:06:59.627082 sonic ERR pmon#xcvrd:     port_info_dict = _wrapper_get_transceiver_info(physical_port)
Oct 11 07:06:59.627371 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 173, in _wrapper_get_transceiver_info
Oct 11 07:06:59.627615 sonic ERR pmon#xcvrd:     return platform_chassis.get_sfp(physical_port).get_transceiver_info()
Oct 11 07:06:59.627966 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 23, in get_transceiver_info
Oct 11 07:06:59.628293 sonic ERR pmon#xcvrd:     api = self.get_xcvr_api()
Oct 11 07:06:59.628607 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/sfp.py", line 538, in get_xcvr_api
Oct 11 07:06:59.628992 sonic ERR pmon#xcvrd:     self.refresh_xcvr_api()
Oct 11 07:06:59.629307 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sfp_base.py", line 458, in refresh_xcvr_api
Oct 11 07:06:59.629617 sonic ERR pmon#xcvrd:     self._xcvr_api = self._xcvr_api_factory.create_xcvr_api()
Oct 11 07:06:59.629924 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/xcvr_api_factory.py", line 66, in create_xcvr_api
Oct 11 07:06:59.630253 sonic ERR pmon#xcvrd:     vendor_pn = self._get_vendor_part_num()
Oct 11 07:06:59.630552 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/xcvr_api_factory.py", line 59, in _get_vendor_part_num
Oct 11 07:06:59.630909 sonic ERR pmon#xcvrd:     vendor_pn = part_num.decode()
Oct 11 07:06:59.631286 sonic ERR pmon#xcvrd: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Oct 11 07:06:59.631286 sonic ERR pmon#xcvrd: Xcvrd: exception found at child thread SfpStateUpdateTask due to UnicodeDecodeError('utf-8', b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff', 0, 1, 'invalid start byte')
Oct 11 07:06:59.631286 sonic ERR pmon#xcvrd: Exiting main loop as child thread raised exception!
```

```
Oct 11 06:55:09.429299 sonic ERR pmon#xcvrd: Exception occured at SfpStateUpdateTask thread due to UnicodeDecodeError('utf-8', b'\x00#\x88\x00\x00\x00\x00\x00\x00\x00\x05\xff\x00\x00\x00\x00', 2, 3, 'invalid start byte')
Oct 11 06:55:09.438703 sonic ERR pmon#xcvrd: Traceback (most recent call last):
Oct 11 06:55:09.439319 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2231, in run
Oct 11 06:55:09.439319 sonic ERR pmon#xcvrd:     self.task_worker(self.task_stopping_event, self.sfp_error_event)
Oct 11 06:55:09.439319 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2043, in task_worker
Oct 11 06:55:09.439319 sonic ERR pmon#xcvrd:     self.init()
Oct 11 06:55:09.439319 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1961, in init
Oct 11 06:55:09.439354 sonic ERR pmon#xcvrd:     self.retry_eeprom_set = self._post_port_sfp_info_and_dom_thr_to_db_once(port_mapping_data, self.xcvr_table_helper, self.main_thread_stop_event)
Oct 11 06:55:09.439376 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1916, in _post_port_sfp_info_and_dom_thr_to_db_once
Oct 11 06:55:09.439376 sonic ERR pmon#xcvrd:     rc = post_port_sfp_info_to_db(logical_port_name, port_mapping, xcvr_table_helper.get_intf_tbl(asic_index), transceiver_dict, stop_event)
Oct 11 06:55:09.439612 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 336, in post_port_sfp_info_to_db
Oct 11 06:55:09.439612 sonic ERR pmon#xcvrd:     port_info_dict = _wrapper_get_transceiver_info(physical_port)
Oct 11 06:55:09.439612 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 173, in _wrapper_get_transceiver_info
Oct 11 06:55:09.439612 sonic ERR pmon#xcvrd:     return platform_chassis.get_sfp(physical_port).get_transceiver_info()
Oct 11 06:55:09.439648 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 23, in get_transceiver_info
Oct 11 06:55:09.439804 sonic ERR pmon#xcvrd:     api = self.get_xcvr_api()
Oct 11 06:55:09.440014 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform/sfp.py", line 538, in get_xcvr_api
Oct 11 06:55:09.440014 sonic ERR pmon#xcvrd:     self.refresh_xcvr_api()
Oct 11 06:55:09.440014 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sfp_base.py", line 458, in refresh_xcvr_api
Oct 11 06:55:09.440014 sonic ERR pmon#xcvrd:     self._xcvr_api = self._xcvr_api_factory.create_xcvr_api()
Oct 11 06:55:09.440049 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/xcvr_api_factory.py", line 65, in create_xcvr_api
Oct 11 06:55:09.440049 sonic ERR pmon#xcvrd:     vendor_name = self._get_vendor_name()
Oct 11 06:55:09.440181 sonic ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/sonic_platform_base/sonic_xcvr/xcvr_api_factory.py", line 52, in _get_vendor_name
Oct 11 06:55:09.440181 sonic ERR pmon#xcvrd:     vendor_name = name_data.decode()
Oct 11 06:55:09.440181 sonic ERR pmon#xcvrd: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 2: invalid start byte
Oct 11 06:55:09.440373 sonic ERR pmon#xcvrd: Xcvrd: exception found at child thread SfpStateUpdateTask due to UnicodeDecodeError('utf-8', b'\x00#\x88\x00\x00\x00\x00\x00\x00\x00\x05\xff\x00\x00\x00\x00', 2, 3, 'invalid start byte')
Oct 11 06:55:09.440373 sonic ERR pmon#xcvrd: Exiting main loop as child thread raised exception!
```

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you expected:

No exception is expected.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vmittal-msft** [comment]
As suggested by Anoop, please try the following and update - 

Hi @keboliu,

Can you try replacing decode function to str(data, 'UTF-8') and check?

vendor_name = str(name_data, 'UTF-8')
vendor_name = name_data.decode()
vendor_pn = str(part_num, 'UTF-8')
vendor_pn = part_num.decode()
