### ISSUE TITLE
[BFD]Syncd crash due to race condition in notification between session down and remove

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#16992]
#### Description

Sometimes during regression it is observed that syncd crashes. This is due a race condition in BFD notification. 

```
2023-10-13.23:41:31.858215|c|SAI_OBJECT_TYPE_BFD_SESSION:oid:0x45000000000e02|SAI_BFD_SESSION_ATTR_TYPE=SAI_BFD_SESSION_TYPE_ASYNC_ACTIVE|SAI_BFD_SESSION_ATTR_LOCAL_DISCRIMINATOR=154|SAI_BFD_SESSION_ATTR_UDP_SRC_PORT=49305|SAI_BFD_SESSION_ATTR_REMOTE_DISCRIMINATOR=0|SAI_BFD_SESSION_ATTR_BFD_ENCAPSULATION_TYPE=SAI_BFD_ENCAPSULATION_TYPE_NONE|SAI_BFD_SESSION_ATTR_IPHDR_VERSION=6|SAI_BFD_SESSION_ATTR_SRC_IP_ADDRESS=2002:2000::10|SAI_BFD_SESSION_ATTR_DST_IP_ADDRESS=2002:2000::11|SAI_BFD_SESSION_ATTR_MIN_TX=1000000|SAI_BFD_SESSION_ATTR_MIN_RX=1000000|SAI_BFD_SESSION_ATTR_MULTIPLIER=10|SAI_BFD_SESSION_ATTR_TOS=192|SAI_BFD_SESSION_ATTR_VIRTUAL_ROUTER=oid:0x3000000000002
Oct 14 02:41:31.858895 r-tigon-21 NOTICE syncd#SDK: [SAI_BFD.NOTICE] ./src/mlnx_sai_bfd.c[1068]- mlnx_create_bfd_session: Create BFD_SESSION: #0 TYPE=ASYNC_ACTIVE #1 LOCAL_DISCRIMINATOR=154 #2 UDP_SRC_PORT=49305 #3 REMOTE_DISCRIMINATOR=0 #4 BFD_ENCAPSULATION_TYPE=NONE #5 IPHDR_VERSION=6 #6 SRC_IP_ADDRESS=2002:2000::10 #7 DST_IP_ADDRESS=2002:2000::11 #8 MIN_TX=1000000 #9 MIN_RX=1000000 #10 MULTIPLIER=10 #11 TOS=192 #12 VIRTUAL_ROUTER=VIRTUAL_ROUTER [OID:0x3] [sx_router_id:0] 
Oct 14 02:41:31.859344 r-tigon-21 NOTICE syncd#SDK: [SAI_BFD.NOTICE] ./src/mlnx_sai_bfd.c[1166]- mlnx_create_bfd_session: Created BFD_SESSION [OID:0x18400000045] [ID:6]

2023-10-13.23:41:55.913258|r|SAI_OBJECT_TYPE_BFD_SESSION:oid:0x45000000000e02
Oct 14 02:41:55.914720 r-tigon-21 NOTICE syncd#SDK: [SAI_BFD.NOTICE] ./src/mlnx_sai_bfd.c[1201]- mlnx_remove_bfd_session: Remove BFD_SESSION [OID:0x18400000045] [ID:6]

Oct 14 02:41:55.914720 r-tigon-21 NOTICE syncd#SDK: [SAI_SWITCH.NOTICE] ./src/mlnx_sai_switch.c[5094]- mlnx_switch_bfd_event_handle: BFD peer [2002:2000::11] is Down

Oct 14 02:41:55.916443 r-tigon-21 ERR syncd#SDK: :- allocateNewObjectId: object type of switch oid:0x0 is SAI_OBJECT_TYPE_NULL, should be SWITCH
Oct 14 02:41:55.918436 r-tigon-21 INFO syncd#supervisord: syncd terminate called after throwing an instance of 'std::runtime_error'
Oct 14 02:41:55.918436 r-tigon-21 INFO syncd#supervisord: syncd   what():  :- allocateNewObjectId: object type of switch oid:0x0 is SAI_OBJECT_TYPE_NULL, should be SWITCH

```
There is a race condition b/w BFD session delete and session state down notifcation coming from ASIC. syncd recieves state down notification after processing the session delete which cause it to throw because translateRidToViD fails Ref: [https://github.com/sonic-net/sonic-sairedis/blob/5887d31ad7c8b63e19390a876270028606d2e4fe/syncd/NotificationProcessor.cpp#L522](https://github.com/sonic-net/sonic-sairedis/blob/5887d31ad7c8b63e19390a876270028606d2e4fe/syncd/NotificationProcessor.cpp#L522et/sonic-sairedis/blob/master/syncd/NotificationProcessor.cpp#L522)

```
#0  0x00007f3447c98ce1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3447c82537 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3447ee87ec in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f3447ef3966 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f3447ef39d1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f3447ef3c65 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f34494b073c in ?? () from /usr/lib/x86_64-linux-gnu/libswsscommon.so.0
#7  0x0000563cb97e1500 in sairedis::VirtualObjectIdManager::allocateNewObjectId (this=<optimized out>, objectType=1113347904, switchId=switchId@entry=0)
    at /usr/include/c++/10/bits/basic_string.h:186
#8  0x0000563cb9735404 in syncd::VirtualOidTranslator::translateRidToVid (this=0x563cbad77120, rid=<optimized out>, switchVid=switchVid@entry=0, 
    translateRemoved=translateRemoved@entry=false) at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#9  0x0000563cb975eb70 in syncd::NotificationProcessor::process_on_bfd_session_state_change (this=0x563cbad72c40, count=1, data=0x7f33c8000bb0)
    at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#10 0x0000563cb975ece4 in syncd::NotificationProcessor::handle_bfd_session_state_change (this=0x563cbad72c40, 
    data="[{\"bfd_session_id\":\"oid:0x18400000045\",\"session_state\":\"SAI_BFD_SESSION_STATE_DOWN\"}]") at NotificationProcessor.cpp:639
#11 0x0000563cb975fba8 in syncd::NotificationProcessor::syncProcessNotification (this=0x563cbad72c40, item=std::tuple containing = {...})
    at NotificationProcessor.cpp:698
#12 0x0000563cb9707467 in syncd::Syncd::syncProcessNotification (this=0x563cbad61650, item=std::tuple containing = {...})
    at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#13 0x0000563cb975d23c in std::function<void (std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)>::operator()(std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&) const (__args#0=std::tuple containing = {...}, this=0x563cbad72cb0) at /usr/include/c++/10/bits/std_function.h:622
#14 syncd::NotificationProcessor::processNotification (this=0x563cbad72c40, item=std::tuple containing = {...}) at NotificationProcessor.cpp:661
#15 0x0000563cb975d3ab in syncd::NotificationProcessor::ntf_process_function (this=0x563cbad72c40) at NotificationProcessor.cpp:727
#16 0x00007f3447f1ced0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007f34480e1ea7 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#18 0x00007f3447d5ba2f in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

We may require to have a fix similar to https://github.com/sonic-net/sonic-sairedis/pull/727 to avoid the race condition.

#### Steps to reproduce the issue:
1. Run BFD tests in a loop
2.
3.

#### Describe the results you received:
Syncd crashes due to race condition

#### Describe the results you expected:
No Syncd crash.

#### Output of `show version`:

```

SONiC Software Version: SONiC.202305_RC.8-8bd96c572_Internal
SONiC OS Version: 11
Distribution: Debian 11.8
Kernel: 5.10.0-18-2-amd64
Build commit: 276eaeec4
Build date: Tue Oct 10 19:06:35 UTC 2023
Built by: sw-r2d2-bot@r-build-sonic-ci03-244

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: Mellanox-SN4600C-C64
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2138X00017
Model Number: MSN4600-CS2FO
Hardware Revision: A1
Uptime: 02:50:31 up 32 min,  2 users,  load average: 1.26, 2.15, 2.08
Date: Sat 14 Oct 2023 02:50:32

Docker images:
REPOSITORY                                         TAG                              IMAGE ID       SIZE
docker-orchagent                                   202305_RC.8-8bd96c572_Internal   160a62bcbba2   343MB
docker-orchagent                                   latest                           160a62bcbba2   343MB
docker-fpm-frr                                     202305_RC.8-8bd96c572_Internal   a8f989f0eba1   362MB
docker-fpm-frr                                     latest                           a8f989f0eba1   362MB
docker-nat                                         202305_RC.8-8bd96c572_Internal   f751e3e0b2c5   334MB
docker-nat                                         latest                           f751e3e0b2c5   334MB
docker-teamd                                       202305_RC.8-8bd96c572_Internal   27f31d5f910e   331MB
docker-teamd                                       latest                           27f31d5f910e   331MB
docker-sflow                                       202305_RC.8-8bd96c572_Internal   52fe339aae94   332MB
docker-sflow                                       latest                           52fe339aae94   332MB
docker-macsec                                      latest                           d3425ce8dffc   333MB
docker-syncd-mlnx                                  202305_RC.8-8bd96c572_Internal   3e67efe75ef7   850MB
docker-syncd-mlnx                                  latest                           3e67efe75ef7   850MB
docker-platform-monitor                            202305_RC.8-8bd96c572_Internal   65bab5d374c3   841MB
docker-platform-monitor                            latest                           65bab5d374c3   841MB
docker-snmp                                        202305_RC.8-8bd96c572_Internal   7a23b7d31c1d   352MB
docker-snmp                                        latest                           7a23b7d31c1d   352MB
docker-dhcp-relay                                  latest                           c9a2b9f352c5   321MB
docker-sonic-telemetry                             202305_RC.8-8bd96c572_Internal   ae6f004b8e58   400MB
docker-sonic-telemetry                             latest                           ae6f004b8e58   400MB
docker-eventd                                      202305_RC.8-8bd96c572_Internal   2eceb2b35b5a   313MB
docker-eventd                                      latest                           2eceb2b35b5a   313MB
docker-mux                                         202305_RC.8-8bd96c572_Internal   4a16dbfce193   362MB
docker-mux                                         latest                           4a16dbfce193   362MB
docker-lldp                                        202305_RC.8-8bd96c572_Internal   fa4ff9a1dcb6   356MB
docker-lldp                                        latest                           fa4ff9a1dcb6   356MB
docker-router-advertiser                           202305_RC.8-8bd96c572_Internal   dff00755ee31   313MB
docker-router-advertiser                           latest                           dff00755ee31   313MB
docker-database                                    202305_RC.8-8bd96c572_Internal   053ff09de423   313MB
docker-database                                    latest                           053ff09de423   313MB
docker-sonic-mgmt-framework                        202305_RC.8-8bd96c572_Internal   906da11fef08   416MB
docker-sonic-mgmt-framework                        latest                           906da11fef08   416MB
urm.nvidia.com/sw-nbu-sws-sonic-docker/sonic-wjh   1.0.0-202305-5                   4bfc92d6fbc4   447MB
urm.nvidia.com/sw-nbu-sws-sonic-docker/doai        1.1.0-202305-6                   3b208bd5416a   277MB


```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sysdump_sonic_dump_r-tigon-21_20231014_025015.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/13127942/sysdump_sonic_dump_r-tigon-21_20231014_025015.tar.gz)

**Comment by prsunny** [comment]
@kcudnik , would you take a look at this?

**Comment by dgsudharsan** [comment]
@kcudnik Can you please provide an ETA for fixing this issue?

**Comment by dgsudharsan** [comment]
@kcudnik Any progress on this bug?

**Comment by kcudnik** [comment]
Did not have time to take a look I will investigate

**Comment by kcudnik** [comment]
Fix here: https://github.com/sonic-net/sonic-sairedis/pull/1320
