### ISSUE TITLE
`dualtor_route_check` failure observed in `fast-reboot`

### ISSUE THREAD

**Issue by lolyu** [sonic-net/sonic-buildimage#17200]
#### Steps to reproduce the issue:
1. run `fast-reboot`
2. run `dualtor_neighbor_check`

#### Describe the results you received:
```
root@lab-dev-acs-11:~# dualtor_neighbor_check.py -l DEBUG
Running command: sudo redis-cli EVALSHA c53fd5eaad68be1e66a2fe80cd20a9cb18c91259 0
Command output: b'NOSCRIPT No matching script. Please use EVAL.\n\n'
Command return code: 0
Traceback (most recent call last):
  File "/usr/local/bin/dualtor_neighbor_check.py", line 490, in <module>
    neighbors, mux_states, hw_mux_states, asic_fdb, asic_route_table, asic_neigh_table = read_tables_from_db(appl_db)
  File "/usr/local/bin/dualtor_neighbor_check.py", line 316, in read_tables_from_db
    tables = json.loads(result)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ZhaohuiS** [comment]
@lolyu which image does it happen on?

**Comment by lolyu** [comment]
> @lolyu which image does it happen on?

`202305` and after.
