### ISSUE TITLE
[202305] [chassis]: route_check.py fails and throw traceback on Supervisor

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#17400]
#### Description
On chassis-packet, there is no bgp running on Supervisor.
route_check.py tries to fetch the routes from frr and throws traceback when empty list is returned.

```
cisco@sfd-t2-sup:~$ sudo su
root@sfd-t2-sup:/home/cisco# route_check.py 
Traceback (most recent call last):
  File "/usr/local/bin/route_check.py", line 810, in <module>
    sys.exit(main()[0])
  File "/usr/local/bin/route_check.py", line 797, in main
    ret, res= check_routes()
  File "/usr/local/bin/route_check.py", line 745, in check_routes
    rt_frr_miss = check_frr_pending_routes()
  File "/usr/local/bin/route_check.py", line 537, in check_frr_pending_routes
    frr_routes = get_frr_routes()
  File "/usr/local/bin/route_check.py", line 344, in get_frr_routes
    routes = json.loads(output)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Introduced by https://github.com/sonic-net/sonic-utilities/pull/2762

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
sha1 from 202305 build:
d814cc41d [eventd]: Disabling eventd tests (#17053) (#17061)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi  , @gechiang  , @rlhui  , for your viz. Thanks

**Comment by prabhataravind** [comment]
@anamehra could you please own this as you have a draft PR in progress? @rlhui for viz

**Comment by anamehra** [comment]
> @anamehra could you please own this as you have a draft PR in progress? @rlhui for viz

Hi @prabhataravind, @rlhui ,  please assign it back to me. I unassigned by error. Thanks
