### ISSUE TITLE
Static DNS test failed

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#17611]
https://github.com/sonic-net/sonic-mgmt/pull/8712

This test_static_dns_basic failed on our internal image, and I have found two issues:

1. exception while checking nameserver

> 01:00:34 utilities.wait_until                     L0135 ERROR  | Exception caught while checking _verify_nameserver_in_conf_file:Traceback (most recent call last):
>  File "/var/src/sonic-mgmt/tests/common/utilities.py", line 131, in wait_until
>    check_result = condition(*args, **kwargs)
>  File "/var/src/sonic-mgmt/tests/dns/static_dns/static_dns_util.py", line 155, in _verify_nameserver_in_conf_file
>    assert set(nameserver_in_host_conf) == set(expected_nameserver), \
>AssertionError: The nameserver in the host's /etc/resolv.conf is: {'1.1.1.1'}, expected is: ['1.1.1.1', 'fe80:1000:2000:3000::1', '172.0.0.1']
, error:The nameserver in the host's /etc/resolv.conf is: {'1.1.1.1'}, expected is: ['1.1.1.1', 'fe80:1000:2000:3000::1', '172.0.0.1']

https://github.com/sonic-net/sonic-mgmt/blob/master/tests/dns/static_dns/static_dns_util.py#L133-L175
Please check above code, verify_nameserver_in_conf_file() is using wait_until, but why do you use assert in _verify_nameserver_in_conf_file()?
 

2. Loganalyzer issue

>E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost xxxxx>']" failed with exit code "1"
>E               Exception:
>E               run module extract_log failed, Ansible Results =>
>E               {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_extract_log_payload_uf_1wvs9/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 306, in main\n  File \"/tmp/ansible_extract_log_payload_uf_1wvs9/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 275, in extract_log\n  File \"/tmp/ansible_extract_log_payload_uf_1wvs9/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 226, in extract_latest_line_with_string\nException: start-LogAnalyzer-test_static_dns_basic.2023-12-17-01:00:25 was not found in /var/log\n"}
>E               Traceback:
>E               Traceback (most recent call last):
>E                 File "/var/src/sonic-mgmt/tests/common/helpers/parallel.py", line 35, in run
>E                   Process.run(self)
>E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
>E                   self._target(*self._args, **self._kwargs)
>E                 File "/var/src/sonic-mgmt/tests/common/helpers/parallel.py", line 245, in wrapper
>E                   target(*args, **kwargs)
>E                 File "/var/src/sonic-mgmt/tests/common/plugins/loganalyzer/__init__.py", line 39, in analyze_logs
>E                   dut_analyzer.analyze(markers[node.hostname])
>E                 File "/var/src/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 321, in analyze
>E                   self.ansible_host.extract_log(directory='/var/log', file_prefix='syslog', start_string=start_string,
>E                 File "/var/src/sonic-mgmt/tests/common/devices/base.py", line 127, in _run
>E                   raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
>E               tests.common.errors.RunAnsibleModuleFail: run module extract_log failed, Ansible Results =>
>E               {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_extract_log_payload_uf_1wvs9/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 306, in main\n  File \"/tmp/ansible_extract_log_payload_uf_1wvs9/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 275, in extract_log\n  File \"/tmp/ansible_extract_log_payload_uf_1wvs9/ansible_extract_log_payload.zip/ansible/modules/extract_log.py\", line 226, in extract_latest_line_with_string\nException: start-LogAnalyzer-test_static_dns_basic.2023-12-17-01:00:25 was not found in /var/log\n"}

Loganalyzer can't find the start marker, maybe you should not use reboot in test_static_dns_basic? Or we need to improve Loganalyzer? Please double check.
#### Steps to reproduce the issue:
1. Run test_static_dns_basic

#### Describe the results you received:
This test case has 2 issues.

#### Describe the results you expected:
This test case should pass.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@dgsudharsan please check on this, looks like these are from new set of DNS tests.
