### ISSUE TITLE
Can not delete the table with config load command

### ISSUE THREAD

**Issue by DennisChiuEC** [sonic-net/sonic-buildimage#17624]
#### Steps to reproduce the issue:
1. config vrf add VrfCfgTest
2. echo "{\"VRF\": \"None\"}" > del_vrf.json
3. config load del_vrf.json -y

#### Describe the results you received:
`admin@admin:~$ echo "{\"VRF\": \"None\"}" > del_vrf.json`
`admin@admin:~$ cat del_vrf.json`
{"VRF": "None"}
`admin@admin:~$ sudo config load del_vrf.json -y`
Running command: /usr/local/bin/sonic-cfggen -j del_vrf.json --write-to-db
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 454, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 443, in main
    configdb.mod_config(FormatConverter.output_to_db(data))
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 2406, in mod_config
    for key, data in table_data.items():
AttributeError: 'str' object has no attribute 'items'

#### Describe the results you expected:
VRF table is deleted from the CONFIG DB

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):
Reference: https://github.com/sonic-net/sonic-swss-common/pull/767

**Comment by liuh-80** [comment]
@DennisChiuEC , This is not a bug, please delete with following commands:


admin@vlab-01:~$ echo "{\"VRF\": {}}" > del_vrf.json
admin@vlab-01:~$ sudo config load del_vrf.json -y
Running command: /usr/local/bin/sonic-cfggen -j del_vrf.json --write-to-db
admin@vlab-01:~$ sonic-db-cli CONFIG_DB keys "*" | grep VRF
admin@vlab-01:~$

**Comment by DennisChiuEC** [comment]
SONiC Software Version: SONiC.master.447642-ee49d0dfe
SONiC OS Version: 12
Distribution: Debian 12.2
Kernel: 6.1.0-11-2-amd64
Build commit: ee49d0dfe
Build date: Thu Jan  4 13:03:52 UTC 2024
Built by: AzDevOps@vmss-soni002SLK


root@sonic:~# config vrf add VrfCfgTest
root@sonic:~# echo "{"VRF": {}}" > del_vrf.json
root@sonic:~# config load del_vrf.json -y
Running command: /usr/local/bin/sonic-cfggen -j del_vrf.json --write-to-db
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 509, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 379, in main
    _process_json(args, data)
  File "/usr/local/bin/sonic-cfggen", line 283, in _process_json
    deep_update(data, FormatConverter.to_deserialized(json.load(stream)))
                                                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by liuh-80** [comment]
Can't find image SONiC.master.447642-ee49d0dfe, will try with image in following  link which is latest master build:
https://dev.azure.com/mssonic/build/_build/results?buildId=447617&view=results

**Comment by liuh-80** [comment]
@DennisChiuEC 

The markdowm editor remove '\' from my input, I verified again


admin@vlab-01:~$ show version

SONiC Software Version: SONiC.master.447617-ee49d0dfe
SONiC OS Version: 12
Distribution: Debian 12.2
Kernel: 6.1.0-11-2-amd64
Build commit: ee49d0dfe
Build date: Thu Jan  4 12:31:31 UTC 2024
Built by: AzDevOps@vmss-soni002SLN

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 09:22:32 up 5 min,  1 user,  load average: 1.53, 1.23, 0.58
Date: Fri 05 Jan 2024 09:22:32


admin@vlab-01:~$ echo "{\"VRF\": {}}" > del_vrf.json
admin@vlab-01:~$ cat ./del_vrf.json
{"VRF": {}}
admin@vlab-01:~$ sudo config load del_vrf.json -y
Running command: /usr/local/bin/sonic-cfggen -j del_vrf.json --write-to-db
admin@vlab-01:~$

**Comment by DennisChiuEC** [comment]
ConfigureVRF first.
root@sonic:# config vrf add VrfCfgTest

**Comment by liuh-80** [comment]
> config vrf add VrfCfgTest


admin@vlab-01:~$ sudo config vrf add VrfCfgTest
admin@vlab-01:~$ sonic-db-cli CONFIG_DB keys "*" | grep VRF
VRF|VrfCfgTest
admin@vlab-01:~$ echo "{\\"VRF\\":null }" > del_vrf.json
admin@vlab-01:~$ cat del_vrf.json
{"VRF":null }
admin@vlab-01:~$ sudo config load del_vrf.json -y
Running command: /usr/local/bin/sonic-cfggen -j del_vrf.json --write-to-db
admin@vlab-01:~$ sudo config vrf add VrfCfgTest
admin@vlab-01:~$

**Comment by DennisChiuEC** [comment]
Is there any reference to show that should use {"VRF":null } rather than {"VRF": {}} or  {"VRF":"NULL"}?

**Comment by liuh-80** [comment]
No, I didn't find document for that, I found out by read code.
Suggest use sonic-db-cli to delete table, usually the sonic-cfggen is used for update.
