### ISSUE TITLE
[201911] Build is failing due to sonic-mgmt-framework compilation error

### ISSUE THREAD

**Issue by volodymyrsamotiy** [sonic-net/sonic-buildimage#17648]
#### Description

201911 build is failing due to sonic-mgmt-framework compilation error.
It is already failing for more than a month: https://sonic-build.azurewebsites.net/ui/sonic/pipelines/139/builds?branchName=201911

Error message:
```
make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/cvl/schema'
Generating sonic-acl.yin ...
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 7, in <module>
    from pyang.scripts.pyang_tool import run
  File "/usr/local/lib/python2.7/dist-packages/pyang/scripts/pyang_tool.py", line 9, in <module>
    from pathlib import Path
ImportError: No module named pathlib
Makefile:43: recipe for target 'sonic-acl.yin' failed
make[3]: *** [sonic-acl.yin] Error 1
make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl/schema'
Makefile:93: recipe for target 'cvl' failed
make[2]: *** [cvl] Error 2
make[2]: Leaving directory '/sonic/src/sonic-mgmt-framework'
dh_auto_build: make -j1 returned exit code 2
debian/rules:3: recipe for target 'binary' failed
make[1]: *** [binary] Error 2
make[1]: Leaving directory '/sonic/src/sonic-mgmt-framework'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
[  FAIL LOG END  ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
slave.mk:360: recipe for target 'target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb' failed
make: *** [target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb] Error 1
```

#### Steps to reproduce the issue:
1. Checkout to 201911 branch (issue is relevant for both latest 201911 commit hash and any older ones)
2. Start build of SONiC binary - e. g. `make target/sonic-mellanox.bin`
3. Or just start build for sonic-mgmt-framework target - `target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb`
4. Observe build failure 

#### Describe the results you received:
```
make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/cvl/schema'
Generating sonic-acl.yin ...
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 7, in <module>
    from pyang.scripts.pyang_tool import run
  File "/usr/local/lib/python2.7/dist-packages/pyang/scripts/pyang_tool.py", line 9, in <module>
    from pathlib import Path
ImportError: No module named pathlib
Makefile:43: recipe for target 'sonic-acl.yin' failed
make[3]: *** [sonic-acl.yin] Error 1
make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl/schema'
Makefile:93: recipe for target 'cvl' failed
make[2]: *** [cvl] Error 2
make[2]: Leaving directory '/sonic/src/sonic-mgmt-framework'
dh_auto_build: make -j1 returned exit code 2
debian/rules:3: recipe for target 'binary' failed
make[1]: *** [binary] Error 2
make[1]: Leaving directory '/sonic/src/sonic-mgmt-framework'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
[  FAIL LOG END  ] [ target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb ]
slave.mk:360: recipe for target 'target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb' failed
make: *** [target/debs/stretch/sonic-mgmt-framework_1.0-01_amd64.deb] Error 1
```

#### Describe the results you expected:
Successful build of 201911 SONiC image

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@adyeung please can you check this failure in 201911 builds
