### ISSUE TITLE
[SfpUtil] sfp eeprom with option dom is not working on Xcvrs with flat memory

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#19032]
#### Steps to reproduce the issue:
```
root@switch/home/admin# sfputil show eeprom -d -p Ethernet0
Traceback (most recent call last):
  File "/usr/local/bin/sfputil", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sfputil/main.py", line 677, in eeprom
    xcvr_dom_info = platform_chassis.get_sfp(physical_port).get_transceiver_bulk_status()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 32, in get_transceiver_bulk_status
    return api.get_transceiver_bulk_status() if api is not None else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sonic_platform_base/sonic_xcvr/api/public/cmis.py", line 233, in get_transceiver_bulk_status
    self.vdm_dict = self.get_vdm(self.vdm.VDM_REAL_VALUE)
                                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'VDM_REAL_VALUE'
```
get_transceiver_bulk_status call is failing

#### Describe the results you received:

Related to https://github.com/sonic-net/sonic-platform-common/pull/397

Fixed a similar issue in xcvrd here: https://github.com/sonic-net/sonic-platform-daemons/pull/458

But sfputil lacks any safeguards. 

Also, no "TRANSCEIVER_DOM_INFO" table entries are seen on these sfp's

#### Describe the results you expected:

No Exception must be throws

#### Output of `show version`:

Latest master

**Comment by prgeor** [comment]
@mihirpat1 can you address this

**Comment by vivekrnv** [comment]
Note: Only seen on master, not on 202311

**Comment by puffc** [comment]
This problem can be seen on 202405. Could you please merge this PR to 202405?

**Comment by mihirpat1** [comment]
@puffc This PR has been already merged to 202405 via https://github.com/sonic-net/sonic-utilities/pull/3434.
Can you please confirm if the image you are using has this fix?
