### ISSUE TITLE
[xcvrd] SfpStateUpdateTask is crashing for RJ45 cable type

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#19427]
#### Description

SfpStateUpdateTask failed to start because of the following exception in xcvrd. This is happening in RJ45 cable type

```
2024 Jun 28 17:36:07.537108 r-alligator-04 ERR pmon#xcvrd: Traceback (most recent call last):
2024 Jun 28 17:36:07.537212 r-alligator-04 ERR pmon#xcvrd:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 2242, in run
2024 Jun 28 17:36:07.537288 r-alligator-04 ERR pmon#xcvrd:     self.task_worker(self.task_stopping_event, self.sfp_error_event)
2024 Jun 28 17:36:07.537401 r-alligator-04 ERR pmon#xcvrd:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 2052, in task_worker
2024 Jun 28 17:36:07.537477 r-alligator-04 ERR pmon#xcvrd:     self.init()
2024 Jun 28 17:36:07.537555 r-alligator-04 ERR pmon#xcvrd:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 1970, in init
2024 Jun 28 17:36:07.537629 r-alligator-04 ERR pmon#xcvrd:     self.retry_eeprom_set = self._post_port_sfp_info_and_dom_thr_to_db_once(port_mapping_data, self.xcvr_table_helper, self.main_thread_stop_event)
2024 Jun 28 17:36:07.537706 r-alligator-04 ERR pmon#xcvrd:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024 Jun 28 17:36:07.537837 r-alligator-04 ERR pmon#xcvrd:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 1927, in _post_port_sfp_info_and_dom_thr_to_db_once
2024 Jun 28 17:36:07.537913 r-alligator-04 ERR pmon#xcvrd:     post_port_dom_threshold_info_to_db(logical_port_name, port_mapping, xcvr_table_helper.get_dom_threshold_tbl(asic_index), stop_event)
2024 Jun 28 17:36:07.537987 r-alligator-04 ERR pmon#xcvrd:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 601, in post_port_dom_threshold_info_to_db
2024 Jun 28 17:36:07.538061 r-alligator-04 ERR pmon#xcvrd:     if _wrapper_is_flat_memory(physical_port) == True:
2024 Jun 28 17:36:07.538134 r-alligator-04 ERR pmon#xcvrd:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024 Jun 28 17:36:07.538212 r-alligator-04 ERR pmon#xcvrd:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 321, in _wrapper_is_flat_memory
2024 Jun 28 17:36:07.538287 r-alligator-04 ERR pmon#xcvrd:     return api.is_flat_memory()
2024 Jun 28 17:36:07.538360 r-alligator-04 ERR pmon#xcvrd:            ^^^^^^^^^^^^^^^^^^
2024 Jun 28 17:36:07.538446 r-alligator-04 ERR pmon#xcvrd: AttributeError: 'NoneType' object has no attribute 'is_flat_memory'
2024 Jun 28 17:36:07.538627 r-alligator-04 ERR pmon#xcvrd[1323]: Xcvrd: exception found at child thread SfpStateUpdateTask due to AttributeError("'NoneType' object has no attribute 'is_flat_memory'")
2024 Jun 28 17:36:07.538735 r-alligator-04 ERR pmon#xcvrd[1323]: Exiting main loop as child thread raised exception!
```

#### Triage

Happening because of this code snippet where get_xcvr_api() returns None for some cable types and is_flat_memory is called on None. 

```
def _wrapper_is_flat_memory(physical_port):
    if platform_chassis is not None:
        try:
            sfp = platform_chassis.get_sfp(physical_port)
            api = sfp.get_xcvr_api()
            return api.is_flat_memory()
        except NotImplementedError:
            pass
    return None
```

**Comment by vivekrnv** [comment]
@prgeor @mihirpat1 Please check

**Comment by mihirpat1** [comment]
@vivekrnv It seems that we don't have a device with RJ45 cable type. Would you be able to take up the fix for this?
In order to fix this `_wrapper_is_flat_memory` function can return True if `api` is `None`.

**Comment by vivekrnv** [comment]
Hi @mihirpat1, I will raise a fix for this
