### ISSUE TITLE
[202405] Orchagent crash on `removeNeighbor` due to `SAI_STATUS_INVALID_PARAMETER`

### ISSUE THREAD

**Issue by arista-nwolfe** [sonic-net/sonic-buildimage#19887]
While running `voq/test_voq_chassis_app_db_consistency.py` we saw orchagent crash with the following error:
```
2024 Aug  4 22:46:43.891594 cmp214-6 ERR swss0#orchagent: :- meta_sai_validate_oid: oid is set to null object id on SAI_OBJECT_TYPE_NEXT_HOP
2024 Aug  4 22:46:43.891594 cmp214-6 ERR swss0#orchagent: :- removeNeighbor: Failed to remove next hop 10.0.0.19 on cmp214-6|asic1|PortChannel999, rv:-5
2024 Aug  4 22:46:43.891625 cmp214-6 ERR swss0#orchagent: :- handleSaiRemoveStatus: Encountered failure in remove operation, exiting orchagent, SAI API: SAI_API_NEXT_HOP, status: SAI_STATUS_INVALID_PARAMETER
```

The core had the following backtrace:
```
(gdb) bt
#0  0x00007f8100edce2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f8100e8dfb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f8100e78472 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x000056499ff63735 in handleSaiFailure (abort_on_failure=abort_on_failure@entry=true) at ./orchagent/saihelper.cpp:834
#4  0x00005649a02082a5 in handleSaiRemoveStatus (api=api@entry=SAI_API_NEXT_HOP, status=status@entry=-5, context=context@entry=0x0)
    at ./orchagent/saihelper.cpp:733
#5  0x00005649a00b8ac9 in NeighOrch::removeNeighbor (this=this@entry=0x5649a0a94260, ctx=..., disable=disable@entry=false)
    at ./orchagent/neighorch.cpp:1173
#6  0x00005649a00be2f5 in NeighOrch::doVoqSystemNeighTask (this=this@entry=0x5649a0a94260, consumer=...) at ./orchagent/neighorch.cpp:1861
#7  0x00005649a00bf6ce in NeighOrch::doTask (this=0x5649a0a94260, consumer=...) at ./orchagent/neighorch.cpp:750
#8  0x00005649a005b0fe in Consumer::drain (this=0x5649a0a97250) at ./orchagent/orch.cpp:260
#9  Consumer::drain (this=0x5649a0a97250) at ./orchagent/orch.cpp:257
#10 Consumer::execute (this=0x5649a0a97250) at ./orchagent/orch.cpp:254
#11 0x00005649a004709a in OrchDaemon::start (this=this@entry=0x5649a09f9300) at ./orchagent/orchdaemon.cpp:855
#12 0x000056499ffb4b0a in main (argc=<optimized out>, argv=<optimized out>) at ./orchagent/main.cpp:800
```

The test removes members and IPs from a programmed LAG and moves them to a new LAG for the purpose of testing `config reload`.
E.G.
```
sudo config portchannel -n asic1 member del PortChannel105 Ethernet144
sudo config portchannel -n asic1 member del PortChannel105 Ethernet152
sudo config interface -n asic1 ip remove PortChannel105 10.0.0.18/31
sudo config interface -n asic1 ip remove PortChannel105 fc00::25/126
<wait 30s>
sudo config portchannel -n asic1 add PortChannel999
sudo config portchannel -n asic1 member add PortChannel999 Ethernet144
sudo config portchannel -n asic1 member add PortChannel999 Ethernet152
sudo config interface -n asic1 ip add PortChannel999 10.0.0.18/31
sudo config interface -n asic1 ip add PortChannel999 fc00::25/126
<wait 30s>
<tests config reload or reboot>
sudo config interface -n asic1 ip remove PortChannel999 10.0.0.18/31
<crash seen here>
sudo config interface -n asic1 ip remove PortChannel999 fc00::25/126
sudo config portchannel -n asic1 member del PortChannel999 Ethernet144
sudo config portchannel -n asic1 member del PortChannel999 Ethernet152
sudo config portchannel -n asic1 del PortChannel999
```

However, when manually replaying these commands I can't reproduce the crash.
The test must be doing something else that is important in causing the crash.

**Comment by abdosi** [comment]
@saksarav-nokia : Can you check this on 2020405 on your side ?

**Comment by saksarav-nokia** [comment]
We have not seen this in Nokia chassis.

**Comment by arista-nwolfe** [comment]
We haven't seen this on Arista platforms in quite some time.
Closing this issue.
