### ISSUE TITLE
j2cli unmaintained and broken on Python 3.12 - Consider alternatives?

### ISSUE THREAD

**Issue by cqjjjzr** [sonic-net/sonic-buildimage#20353]
#### Description

I'm trying to build SONiC on Ubuntu 24.04, but the j2 tool fails to render the necessary templates. j2cli has been unmaintained for long, and the usage of removed feature is not likely to be fixed by the original author. A migration to alternatives may be necessary.

Possible candidate: https://github.com/kpfleming/jinjanator which is a fork of j2cli.

#### Steps to reproduce the issue:

Execute `make init` on a machine with Python 3.12 as the default Python installation.

#### Describe the results you received:

The environment normally initializes.

#### Describe the results you expected:

The build fails with the following output:

```
Traceback (most recent call last):
  File "/home/charlie/vsonic/venv/bin/j2", line 5, in <module>
    from j2cli import main
  File "/home/charlie/vsonic/venv/lib/python3.12/site-packages/j2cli/__init__.py", line 10, in <module>
    from j2cli.cli import main
  File "/home/charlie/vsonic/venv/lib/python3.12/site-packages/j2cli/cli.py", line 8, in <module>
    import imp, inspect
ModuleNotFoundError: No module named 'imp'
```

The builtin module `imp` was deprecated in Python 3.4 and removed in Python 3.12. However, the j2cli has been unmaintained since January (see https://github.com/kolypto/j2cli/issues/80), so the issue is not likely to be fixed.

#### Workaround

Create the Python venv using version <= 3.11.

**Comment by judyjoseph** [comment]
Please add more details as to which branch you are seeing this issue. @sonic-build please check @xumia

**Comment by cqjjjzr** [comment]
I've see this problem on branch master and 202405, but I expect it to appear on all branches since they are all using `j2cli` to apply the templates.
