### ISSUE TITLE
[macsec] config crashes when deleting port with no profile

### ISSUE THREAD

**Issue by liamkearney-msft** [sonic-net/sonic-buildimage#20631]
#### Description

macsec config command crashes and backtraces when trying to delete a port which doesnt have macsec configured

#### Steps to reproduce the issue:
1. Bring up dut with macsec but a port without a profile
2. run config macsec port del <port>

#### Describe the results you received:
A backtrace / crash of config: 
```
Traceback (most recent call last):
  File "/usr/local/bin/config", line 8, in <module>
    sys.exit(config())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/config/plugins/macsec.py", line 87, in del_port
    del port_entry['macsec']
KeyError: 'macsec'
```

#### Describe the results you expected:
graceful failure

#### Output of `show version`:
SONiC Software Version: SONiC.20220532.72

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
This is a negative test, will address this in master/202405

**Comment by rlhui** [comment]
PR avail, close this.
