### ISSUE TITLE
[Bug]: Syslog Error "ERR ntpd[634528]: nss_tacplus: /etc/tacplus_nss.conf fopen failed" 

### ISSUE THREAD

**Issue by kaushiksrivatsav** [sonic-net/sonic-buildimage#21698]
### Issue Description

we are seeing syslog error ERR ntpd[634528]: nss_tacplus: /etc/tacplus_nss.conf fopen failed 
while running snmp/test_snmp_link_local.py::test_snmp_link_local_ip[str-marvell-acs-1]

### Results you see

E               2024 Jun 20 07:52:00.230278 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: /etc/tacplus_nss.conf fopen failed
E
E               2024 Jun 20 07:52:00.230409 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: bad config or server line for nss_tacplus

### Results you expected to see

no syslog errors 

### Is it platform specific

marvell

### Relevant log output

```shell
# if we have failed processes, we should log the exception and exit code
        # of each Process and fail
        if len(list(failed_processes.keys())):
            for process_name, process in list(failed_processes.items()):
                p_exitcode = ""
                p_exception = ""
                p_traceback = ""
                if 'exception' in process and process['exception']:
                    p_exception = process['exception'][0]
                    p_traceback = process['exception'][1]
                    p_exitcode = process['exit_code']
>               pt_assert(
                    False,
                    'Processes "{}" failed with exit code "{}"\nException:\n{}\nTraceback:\n{}'.format(
                        list(failed_processes.keys()), p_exitcode, p_exception, p_traceback
                    )
                )
E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>']" failed with exit code "1"
E               Exception:
E               match: 2
E               expected_match: 0
E               expected_missing_match: 0
E
E               Match Messages:
E               2024 Jun 20 07:52:00.230278 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: /etc/tacplus_nss.conf fopen failed
E
E               2024 Jun 20 07:52:00.230409 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: bad config or server line for nss_tacplus
E
E               Traceback:
E               Traceback (most recent call last):
E                 File "/var/AzDevOps/sonic-mgmt/tests/common/helpers/parallel.py", line 35, in run
E                   Process.run(self)
E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/var/AzDevOps/sonic-mgmt/tests/common/helpers/parallel.py", line 245, in wrapper
E                   target(*args, **kwargs)
E                 File "/var/AzDevOps/sonic-mgmt/tests/common/plugins/loganalyzer/__init__.py", line 45, in analyze_logs
E                   dut_analyzer.analyze(markers[node.hostname], fail_test, store_la_logs=store_la_logs)
E                 File "/var/AzDevOps/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 409, in analyze
E                   self._verify_log(analyzer_summary)
E                 File "/var/AzDevOps/sonic-mgmt/tests/common/plugins/loganalyzer/loganalyzer.py", line 140, in _verify_log
E                   raise LogAnalyzerError(result_str)
E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 2
E               expected_match: 0
E               expected_missing_match: 0
E
E               Match Messages:
E               2024 Jun 20 07:52:00.230278 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: /etc/tacplus_nss.conf fopen failed
E
E               2024 Jun 20 07:52:00.230409 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: bad config or server line for nss_tacplus

alive      = []
args       = [{'str-marvell-acs-1': <tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzer object at 0x7f81955de0a0>}, {'str-marvell-acs-1': 'test_snmp_link_local_ip[str-marvell-acs-1].2024-06-20-07:51:19'}]
concurrent_tasks = 24
delta_time = datetime.timedelta(seconds=7, microseconds=68377)
end_time   = datetime.datetime(2024, 6, 20, 7, 52, 10, 543426)
failed_processes = {'analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>': {'exception': ('Log Analyzer Error- Matches found, please che...0409 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: bad config or server line for nss_tacplus\n\n'), 'exit_code': 1}}
force_terminate = <function parallel_run.<locals>.force_terminate at 0x7f81954a2670>
gone       = [<SonicProcess name='analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>' pid=11525 parent=10670 stopped exitcode=1>]
init_result = None
kwargs     = {'fail_test': True, 'node': <MultiAsicSonicHost str-marvell-acs-1>, 'results': <DictProxy object, typeid 'dict' at 0x7f81954fb430>, 'store_la_logs': False}
node       = <MultiAsicSonicHost str-marvell-acs-1>
nodes      = []
nodes_list = [<MultiAsicSonicHost str-marvell-acs-1>]
on_terminate = <function parallel_run.<locals>.on_terminate at 0x7f81954a25e0>
p_exception = 'Log Analyzer Error- Matches found, please check errors in log'
p_exitcode = 1
p_traceback = 'Traceback (most recent call last):\n  File "/var/AzDevOps/sonic-mgmt/tests/common/helpers/parallel.py", line 35, in r... Jun 20 07:52:00.230409 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: bad config or server line for nss_tacplus\n\n'
process    = {'exception': ('Log Analyzer Error- Matches found, please check errors in log', 'Traceback (most recent call last):\n ...30409 str-marvell-acs-1 ERR ntpd[634528]: nss_tacplus: bad config or server line for nss_tacplus\n\n'), 'exit_code': 1}
process_name = 'analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>'
results    = <DictProxy object, typeid 'dict' at 0x7f81954fb430>
start_time = datetime.datetime(2024, 6, 20, 7, 52, 3, 475049)
target     = <function reset_ansible_local_tmp.<locals>.wrapper at 0x7f819ab95430>
tasks_done = 1
tasks_running = 0
timeout    = 120
total_tasks = 1
total_timeout = 120
worker     = <SonicProcess name='analyze_logs--<MultiAsicSonicHost str-marvell-acs-1>' pid=11525 parent=10670 stopped exitcode=1>
workers    = []

common/helpers/parallel.py:214: Failed
```

### Output of `show version`

```shell
SONiC Software Version: SONiC.202405.0-dirty-20240612.064353
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: 7bafdab86
Build date: Wed Jun 12 07:07:26 UTC 2024
Built by: marvell@cpss-testvm1

Platform: x86_64-marvell_db98cx8540_16cd-r0
HwSKU: db98cx8540_16cd
ASIC: marvell
ASIC Count: 1
Serial Number: NA
Model Number: NA
Hardware Revision: N/A
Uptime: 03:42:55 up 13:49,  1 user,  load average: 1.46, 1.45, 1.44
Date: Thu 20 Jun 2024 03:42:55

Docker images:
REPOSITORY                    TAG                              IMAGE ID       SIZE
docker-syncd-mrvl-rpc         202405.0-dirty-20240612.064353   f643d7ce193c   585MB
docker-syncd-mrvl-rpc         latest                           f643d7ce193c   585MB
docker-macsec                 latest                           eb50c20a2246   347MB
docker-dhcp-relay             latest                           58e72a51d4af   325MB
docker-teamd                  202405.0-dirty-20240612.064353   9384f2f48e12   344MB
docker-teamd                  latest                           9384f2f48e12   344MB
docker-sonic-mgmt-framework   202405.0-dirty-20240612.064353   13aa80364eb5   402MB
docker-sonic-mgmt-framework   latest                           13aa80364eb5   402MB
docker-snmp                   202405.0-dirty-20240612.064353   e1ddbd3c38f9   355MB
docker-snmp                   latest                           e1ddbd3c38f9   355MB
docker-sflow                  202405.0-dirty-20240612.064353   4882fb502e7c   345MB
docker-sflow                  latest                           4882fb502e7c   345MB
docker-router-advertiser      202405.0-dirty-20240612.064353   b44a98aca7c4   316MB
docker-router-advertiser      latest                           b44a98aca7c4   316MB
docker-platform-monitor       202405.0-dirty-20240612.064353   499aac892c88   441MB
docker-platform-monitor       latest                           499aac892c88   441MB
docker-orchagent              202405.0-dirty-20240612.064353   2b06b769aae5   357MB
docker-orchagent              latest                           2b06b769aae5   357MB
docker-nat                    202405.0-dirty-20240612.064353   6ff5537aa194   347MB
docker-nat                    latest                           6ff5537aa194   347MB
docker-mux                    202405.0-dirty-20240612.064353   8d9a7bc2bcb1   367MB
docker-mux                    latest                           8d9a7bc2bcb1   367MB
docker-lldp                   202405.0-dirty-20240612.064353   b5fa4ebe7191   361MB
docker-lldp                   latest                           b5fa4ebe7191   361MB
docker-sonic-gnmi             202405.0-dirty-20240612.064353   93bbd8c3d57f   400MB
docker-sonic-gnmi             latest                           93bbd8c3d57f   400MB
docker-fpm-frr                202405.0-dirty-20240612.064353   494a1138b32e   376MB
docker-fpm-frr                latest                           494a1138b32e   376MB
docker-eventd                 202405.0-dirty-20240612.064353   089be6e4318c   315MB
docker-eventd                 latest                           089be6e4318c   315MB
docker-database               202405.0-dirty-20240612.064353   257a27b56050   324MB
docker-database               latest                           257a27b56050   324MB
```

**Comment by liuh-80** [comment]
TACACS hooked system API getpwnam, if nptd invoke this API, the ntpd will access /etc/tacplus_nss.conf

The test case will reload config after test, which will re-render /etc/tacplus_nss.conf.
If ntpd invoke getpwnam during re-render /etc/tacplus_nss.conf, this error message will happen.

There is already a fix for this issue: https://github.com/sonic-net/sonic-mgmt/pull/16239

Will add backport to 202405 request label.

**Comment by qiluo-msft** [comment]
202405 PR is merged https://github.com/sonic-net/sonic-mgmt/pull/16927
