### ISSUE TITLE
[sonic-utilities] config reload got exception if "state" field is not present in FEATURE table of CONFIG_DB

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#8362]
#### Description

Execute "config reload -y" got exception:
```
Traceback (most recent call last):
  File "/usr/bin/config", line 12, in <module>
    sys.exit(config())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 914, in reload
    _restart_services()
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 618, in _restart_services
    disable_services = _get_disabled_services_list()
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 540, in _get_disabled_services_list
    state = feature_table[feature_name]['state']
```

The root cause on my environment is that "state" is not a field of "FEATURE|rest_api" in CONFIG_DB:

```
127.0.0.1:6379[4]> HGETALL FEATURE|restapi
1) "auto_restart"
2) "disabled"
3) "high_mem_alert"
4) "disabled"
```

So the question is that: is state a mandatory field of FEATURE table. If yes, this is a configuration issue; else we need fix the code at line https://github.com/Azure/sonic-utilities/blob/4b88e0eaae942c1cde32953f3814d438b35c234b/config/main.py#L657

A possible fix is to change it to:
```python
state = feature_table[feature_name].get('state')
```

#### Steps to reproduce the issue:
1. remove state field of any feature entry in CONFIG_DB
2. run config reload -y

#### Describe the results you received:

Got exception described below

#### Describe the results you expected:

No exception

#### Output of `show version`:

```
See the issue on 201911, 202012 and master 
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Junchao-Mellanox** [comment]
i guess state is a mandatory field. so I am closing this issue.
